// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/internal/logic/regionservice"
	"oa.98ent.com/p9/platform-base/rpc/internal/svc"
	"oa.98ent.com/p9/platform-base/rpc/pb/base"
	"oa.98ent.com/p9/platform-base/rpc/pb/base/region"
)

type RegionServiceServer struct {
	svcCtx *svc.ServiceContext
	base.UnimplementedRegionServiceServer
}

func NewRegionServiceServer(svcCtx *svc.ServiceContext) *RegionServiceServer {
	return &RegionServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建国家地区
func (s *RegionServiceServer) Create(ctx context.Context, in *region.CreateRegionRequest) (*region.CreateRegionResponse, error) {
	l := regionservicelogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

// 修改国家地区
func (s *RegionServiceServer) Update(ctx context.Context, in *region.UpdateRegionRequest) (*region.UpdateRegionResponse, error) {
	l := regionservicelogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

// 获取国家地区
func (s *RegionServiceServer) Get(ctx context.Context, in *region.GetRegionRequest) (*region.GetRegionResponse, error) {
	l := regionservicelogic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

// 获取国家地区管理列表
func (s *RegionServiceServer) List(ctx context.Context, in *region.ListRegionsRequest) (*region.ListRegionsResponse, error) {
	l := regionservicelogic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 获取全部国家地区
func (s *RegionServiceServer) ListAll(ctx context.Context, in *region.ListAllRegionsRequest) (*region.ListAllRegionsResponse, error) {
	l := regionservicelogic.NewListAllLogic(ctx, s.svcCtx)
	return l.ListAll(in)
}

// 调整国家地区排序
func (s *RegionServiceServer) Reorder(ctx context.Context, in *region.ReorderRegionRequest) (*region.ReorderRegionResponse, error) {
	l := regionservicelogic.NewReorderLogic(ctx, s.svcCtx)
	return l.Reorder(in)
}
