// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateCurrencyRequest struct {
	Code         string            `json:"code" validate:"required,max=16"`
	NameI18n     map[string]string `json:"name_i18n" validate:"required"`
	CurrencyType int64             `json:"currency_type" validate:"required,oneof=1 2"`
	Symbol       string            `json:"symbol" validate:"required,max=16"`
	AmountFactor int64             `json:"amount_factor" validate:"required,gt=0"`
	Status       *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type CreateCurrencyResponse struct {
	Id int64 `json:"id"`
}

type CreateLanguageRequest struct {
	Code     string            `json:"code" validate:"required,max=35"`
	NameI18n map[string]string `json:"name_i18n" validate:"required"`
	Status   *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type CreateLanguageResponse struct {
	Id int64 `json:"id"`
}

type CreateRegionRequest struct {
	Code        string            `json:"code" validate:"required,len=2"`
	CallingCode string            `json:"calling_code" validate:"required,max=3"`
	NameI18n    map[string]string `json:"name_i18n" validate:"required"`
	Status      *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type CreateRegionResponse struct {
	Id int64 `json:"id"`
}

type CreateTimezoneRequest struct {
	Code     string            `json:"code" validate:"required,max=64"`
	NameI18n map[string]string `json:"name_i18n" validate:"required"`
	Status   *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type CreateTimezoneResponse struct {
	Id int64 `json:"id"`
}

type CurrencyInfo struct {
	Id           int64             `json:"id"`
	Code         string            `json:"code"`
	NameI18n     map[string]string `json:"name_i18n"`
	CurrencyType int64             `json:"currency_type"`
	Symbol       string            `json:"symbol"`
	AmountFactor int64             `json:"amount_factor"`
	Status       int64             `json:"status"`
	SortNo       int64             `json:"sort_no"`
}

type GetCurrencyRequest struct {
	Id int64 `form:"id" validate:"required,gt=0"`
}

type GetCurrencyResponse struct {
	Currency CurrencyInfo `json:"currency"`
}

type GetLanguageRequest struct {
	Id int64 `form:"id" validate:"required,gt=0"`
}

type GetLanguageResponse struct {
	Language LanguageInfo `json:"language"`
}

type GetRegionRequest struct {
	Id int64 `form:"id" validate:"required,gt=0"`
}

type GetRegionResponse struct {
	Region RegionInfo `json:"region"`
}

type GetTimezoneRequest struct {
	Id int64 `form:"id" validate:"required,gt=0"`
}

type GetTimezoneResponse struct {
	Timezone TimezoneInfo `json:"timezone"`
}

type LanguageInfo struct {
	Id       int64             `json:"id"`
	Code     string            `json:"code"`
	NameI18n map[string]string `json:"name_i18n"`
	Status   int64             `json:"status"`
	SortNo   int64             `json:"sort_no"`
}

type ListAllCurrenciesRequest struct {
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListAllCurrenciesResponse struct {
	List []CurrencyInfo `json:"list"`
}

type ListAllLanguagesRequest struct {
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListAllLanguagesResponse struct {
	List []LanguageInfo `json:"list"`
}

type ListAllRegionsRequest struct {
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListAllRegionsResponse struct {
	List []RegionInfo `json:"list"`
}

type ListAllTimezonesRequest struct {
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListAllTimezonesResponse struct {
	List []TimezoneInfo `json:"list"`
}

type ListCurrenciesRequest struct {
	PageRequest
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListCurrenciesResponse struct {
	Total int64          `json:"total"`
	List  []CurrencyInfo `json:"list"`
}

type ListLanguagesRequest struct {
	PageRequest
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListLanguagesResponse struct {
	Total int64          `json:"total"`
	List  []LanguageInfo `json:"list"`
}

type ListRegionsRequest struct {
	PageRequest
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListRegionsResponse struct {
	Total int64        `json:"total"`
	List  []RegionInfo `json:"list"`
}

type ListTimezonesRequest struct {
	PageRequest
	Status *int64 `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListTimezonesResponse struct {
	Total int64          `json:"total"`
	List  []TimezoneInfo `json:"list"`
}

type PageRequest struct {
	Page     int64 `form:"page" validate:"required,gte=1"`
	PageSize int64 `form:"page_size" validate:"required,gte=1,lte=100"`
}

type PingResponse struct {
}

type RegionInfo struct {
	Id          int64             `json:"id"`
	Code        string            `json:"code"`
	CallingCode string            `json:"calling_code"`
	NameI18n    map[string]string `json:"name_i18n"`
	Status      int64             `json:"status"`
	SortNo      int64             `json:"sort_no"`
}

type ReorderCurrencyRequest struct {
	Id       int64 `json:"id" validate:"required,gt=0"`
	TargetId int64 `json:"target_id" validate:"required,gt=0"`
}

type ReorderCurrencyResponse struct {
}

type ReorderLanguageRequest struct {
	Id       int64 `json:"id" validate:"required,gt=0"`
	TargetId int64 `json:"target_id" validate:"required,gt=0"`
}

type ReorderLanguageResponse struct {
}

type ReorderRegionRequest struct {
	Id       int64 `json:"id" validate:"required,gt=0"`
	TargetId int64 `json:"target_id" validate:"required,gt=0"`
}

type ReorderRegionResponse struct {
}

type ReorderTimezoneRequest struct {
	Id       int64 `json:"id" validate:"required,gt=0"`
	TargetId int64 `json:"target_id" validate:"required,gt=0"`
}

type ReorderTimezoneResponse struct {
}

type TimezoneInfo struct {
	Id       int64             `json:"id"`
	Code     string            `json:"code"`
	NameI18n map[string]string `json:"name_i18n"`
	Status   int64             `json:"status"`
	SortNo   int64             `json:"sort_no"`
}

type UpdateCurrencyRequest struct {
	Id           int64             `json:"id" validate:"required,gt=0"`
	NameI18n     map[string]string `json:"name_i18n,optional"`
	CurrencyType *int64            `json:"currency_type,optional" validate:"omitempty,oneof=1 2"`
	Symbol       *string           `json:"symbol,optional" validate:"omitempty,max=16"`
	AmountFactor *int64            `json:"amount_factor,optional" validate:"omitempty,gt=0"`
	Status       *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type UpdateCurrencyResponse struct {
}

type UpdateLanguageRequest struct {
	Id       int64             `json:"id" validate:"required,gt=0"`
	NameI18n map[string]string `json:"name_i18n,optional"`
	Status   *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type UpdateLanguageResponse struct {
}

type UpdateRegionRequest struct {
	Id          int64             `json:"id" validate:"required,gt=0"`
	CallingCode *string           `json:"calling_code,optional" validate:"omitempty,max=3"`
	NameI18n    map[string]string `json:"name_i18n,optional"`
	Status      *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type UpdateRegionResponse struct {
}

type UpdateTimezoneRequest struct {
	Id       int64             `json:"id" validate:"required,gt=0"`
	NameI18n map[string]string `json:"name_i18n,optional"`
	Status   *int64            `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type UpdateTimezoneResponse struct {
}
