// Code generated by ent, DO NOT EDIT.

package currency

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the currency type in the database.
	Label = "currency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSortNo holds the string denoting the sort_no field in the database.
	FieldSortNo = "sort_no"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldNameI18n holds the string denoting the name_i18n field in the database.
	FieldNameI18n = "name_i18n"
	// FieldCurrencyType holds the string denoting the currency_type field in the database.
	FieldCurrencyType = "currency_type"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldAmountFactor holds the string denoting the amount_factor field in the database.
	FieldAmountFactor = "amount_factor"
	// Table holds the table name of the currency in the database.
	Table = "currency"
)

// Columns holds all SQL columns for currency fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldSortNo,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCode,
	FieldNameI18n,
	FieldCurrencyType,
	FieldSymbol,
	FieldAmountFactor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int64
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// CurrencyTypeValidator is a validator for the "currency_type" field. It is called by the builders before save.
	CurrencyTypeValidator func(int64) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
	// AmountFactorValidator is a validator for the "amount_factor" field. It is called by the builders before save.
	AmountFactorValidator func(int64) error
)

// OrderOption defines the ordering options for the Currency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortNo orders the results by the sort_no field.
func BySortNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortNo, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByCurrencyType orders the results by the currency_type field.
func ByCurrencyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyType, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByAmountFactor orders the results by the amount_factor field.
func ByAmountFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountFactor, opts...).ToFunc()
}
