// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	currency "oa.98ent.com/p9/platform-base/api/internal/handler/currency"
	language "oa.98ent.com/p9/platform-base/api/internal/handler/language"
	ping "oa.98ent.com/p9/platform-base/api/internal/handler/ping"
	region "oa.98ent.com/p9/platform-base/api/internal/handler/region"
	timezone "oa.98ent.com/p9/platform-base/api/internal/handler/timezone"
	"oa.98ent.com/p9/platform-base/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: currency.CreateCurrencyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: currency.GetCurrencyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: currency.ListCurrenciesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list-all",
				Handler: currency.ListAllCurrenciesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reorder",
				Handler: currency.ReorderCurrencyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: currency.UpdateCurrencyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/currency"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: language.CreateLanguageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: language.GetLanguageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: language.ListLanguagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list-all",
				Handler: language.ListAllLanguagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reorder",
				Handler: language.ReorderLanguageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: language.UpdateLanguageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/language"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: ping.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: region.CreateRegionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: region.GetRegionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: region.ListRegionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list-all",
				Handler: region.ListAllRegionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reorder",
				Handler: region.ReorderRegionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: region.UpdateRegionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/region"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: timezone.CreateTimezoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: timezone.GetTimezoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: timezone.ListTimezonesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list-all",
				Handler: timezone.ListAllTimezonesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reorder",
				Handler: timezone.ReorderTimezoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: timezone.UpdateTimezoneHandler(serverCtx),
			},
		},
		rest.WithPrefix("/timezone"),
	)
}
