// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-base/rpc/ent/currency"
	"oa.98ent.com/p9/platform-base/rpc/ent/predicate"
)

// CurrencyUpdate is the builder for updating Currency entities.
type CurrencyUpdate struct {
	config
	hooks    []Hook
	mutation *CurrencyMutation
}

// Where appends a list predicates to the CurrencyUpdate builder.
func (_u *CurrencyUpdate) Where(ps ...predicate.Currency) *CurrencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CurrencyUpdate) SetStatus(v int64) *CurrencyUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CurrencyUpdate) SetNillableStatus(v *int64) *CurrencyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CurrencyUpdate) AddStatus(v int64) *CurrencyUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *CurrencyUpdate) SetSortNo(v int64) *CurrencyUpdate {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *CurrencyUpdate) SetNillableSortNo(v *int64) *CurrencyUpdate {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *CurrencyUpdate) AddSortNo(v int64) *CurrencyUpdate {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CurrencyUpdate) SetUpdatedAt(v time.Time) *CurrencyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *CurrencyUpdate) SetCode(v string) *CurrencyUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CurrencyUpdate) SetNillableCode(v *string) *CurrencyUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetNameI18n sets the "name_i18n" field.
func (_u *CurrencyUpdate) SetNameI18n(v map[string]string) *CurrencyUpdate {
	_u.mutation.SetNameI18n(v)
	return _u
}

// SetCurrencyType sets the "currency_type" field.
func (_u *CurrencyUpdate) SetCurrencyType(v int64) *CurrencyUpdate {
	_u.mutation.ResetCurrencyType()
	_u.mutation.SetCurrencyType(v)
	return _u
}

// SetNillableCurrencyType sets the "currency_type" field if the given value is not nil.
func (_u *CurrencyUpdate) SetNillableCurrencyType(v *int64) *CurrencyUpdate {
	if v != nil {
		_u.SetCurrencyType(*v)
	}
	return _u
}

// AddCurrencyType adds value to the "currency_type" field.
func (_u *CurrencyUpdate) AddCurrencyType(v int64) *CurrencyUpdate {
	_u.mutation.AddCurrencyType(v)
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *CurrencyUpdate) SetSymbol(v string) *CurrencyUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *CurrencyUpdate) SetNillableSymbol(v *string) *CurrencyUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetAmountFactor sets the "amount_factor" field.
func (_u *CurrencyUpdate) SetAmountFactor(v int64) *CurrencyUpdate {
	_u.mutation.ResetAmountFactor()
	_u.mutation.SetAmountFactor(v)
	return _u
}

// SetNillableAmountFactor sets the "amount_factor" field if the given value is not nil.
func (_u *CurrencyUpdate) SetNillableAmountFactor(v *int64) *CurrencyUpdate {
	if v != nil {
		_u.SetAmountFactor(*v)
	}
	return _u
}

// AddAmountFactor adds value to the "amount_factor" field.
func (_u *CurrencyUpdate) AddAmountFactor(v int64) *CurrencyUpdate {
	_u.mutation.AddAmountFactor(v)
	return _u
}

// Mutation returns the CurrencyMutation object of the builder.
func (_u *CurrencyUpdate) Mutation() *CurrencyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CurrencyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CurrencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CurrencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CurrencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CurrencyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := currency.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CurrencyUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := currency.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Currency.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := currency.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Currency.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := currency.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Currency.symbol": %w`, err)}
		}
	}
	return nil
}

func (_u *CurrencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(currency.Table, currency.Columns, sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(currency.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(currency.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(currency.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(currency.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(currency.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(currency.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameI18n(); ok {
		_spec.SetField(currency.FieldNameI18n, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CurrencyType(); ok {
		_spec.SetField(currency.FieldCurrencyType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCurrencyType(); ok {
		_spec.AddField(currency.FieldCurrencyType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(currency.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountFactor(); ok {
		_spec.SetField(currency.FieldAmountFactor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountFactor(); ok {
		_spec.AddField(currency.FieldAmountFactor, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{currency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CurrencyUpdateOne is the builder for updating a single Currency entity.
type CurrencyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CurrencyMutation
}

// SetStatus sets the "status" field.
func (_u *CurrencyUpdateOne) SetStatus(v int64) *CurrencyUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CurrencyUpdateOne) SetNillableStatus(v *int64) *CurrencyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CurrencyUpdateOne) AddStatus(v int64) *CurrencyUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *CurrencyUpdateOne) SetSortNo(v int64) *CurrencyUpdateOne {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *CurrencyUpdateOne) SetNillableSortNo(v *int64) *CurrencyUpdateOne {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *CurrencyUpdateOne) AddSortNo(v int64) *CurrencyUpdateOne {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CurrencyUpdateOne) SetUpdatedAt(v time.Time) *CurrencyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *CurrencyUpdateOne) SetCode(v string) *CurrencyUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CurrencyUpdateOne) SetNillableCode(v *string) *CurrencyUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetNameI18n sets the "name_i18n" field.
func (_u *CurrencyUpdateOne) SetNameI18n(v map[string]string) *CurrencyUpdateOne {
	_u.mutation.SetNameI18n(v)
	return _u
}

// SetCurrencyType sets the "currency_type" field.
func (_u *CurrencyUpdateOne) SetCurrencyType(v int64) *CurrencyUpdateOne {
	_u.mutation.ResetCurrencyType()
	_u.mutation.SetCurrencyType(v)
	return _u
}

// SetNillableCurrencyType sets the "currency_type" field if the given value is not nil.
func (_u *CurrencyUpdateOne) SetNillableCurrencyType(v *int64) *CurrencyUpdateOne {
	if v != nil {
		_u.SetCurrencyType(*v)
	}
	return _u
}

// AddCurrencyType adds value to the "currency_type" field.
func (_u *CurrencyUpdateOne) AddCurrencyType(v int64) *CurrencyUpdateOne {
	_u.mutation.AddCurrencyType(v)
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *CurrencyUpdateOne) SetSymbol(v string) *CurrencyUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *CurrencyUpdateOne) SetNillableSymbol(v *string) *CurrencyUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetAmountFactor sets the "amount_factor" field.
func (_u *CurrencyUpdateOne) SetAmountFactor(v int64) *CurrencyUpdateOne {
	_u.mutation.ResetAmountFactor()
	_u.mutation.SetAmountFactor(v)
	return _u
}

// SetNillableAmountFactor sets the "amount_factor" field if the given value is not nil.
func (_u *CurrencyUpdateOne) SetNillableAmountFactor(v *int64) *CurrencyUpdateOne {
	if v != nil {
		_u.SetAmountFactor(*v)
	}
	return _u
}

// AddAmountFactor adds value to the "amount_factor" field.
func (_u *CurrencyUpdateOne) AddAmountFactor(v int64) *CurrencyUpdateOne {
	_u.mutation.AddAmountFactor(v)
	return _u
}

// Mutation returns the CurrencyMutation object of the builder.
func (_u *CurrencyUpdateOne) Mutation() *CurrencyMutation {
	return _u.mutation
}

// Where appends a list predicates to the CurrencyUpdate builder.
func (_u *CurrencyUpdateOne) Where(ps ...predicate.Currency) *CurrencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CurrencyUpdateOne) Select(field string, fields ...string) *CurrencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Currency entity.
func (_u *CurrencyUpdateOne) Save(ctx context.Context) (*Currency, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CurrencyUpdateOne) SaveX(ctx context.Context) *Currency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CurrencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CurrencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CurrencyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := currency.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CurrencyUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := currency.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Currency.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := currency.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Currency.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := currency.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Currency.symbol": %w`, err)}
		}
	}
	return nil
}

func (_u *CurrencyUpdateOne) sqlSave(ctx context.Context) (_node *Currency, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(currency.Table, currency.Columns, sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Currency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, currency.FieldID)
		for _, f := range fields {
			if !currency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != currency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(currency.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(currency.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(currency.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(currency.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(currency.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(currency.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameI18n(); ok {
		_spec.SetField(currency.FieldNameI18n, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CurrencyType(); ok {
		_spec.SetField(currency.FieldCurrencyType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCurrencyType(); ok {
		_spec.AddField(currency.FieldCurrencyType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(currency.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountFactor(); ok {
		_spec.SetField(currency.FieldAmountFactor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountFactor(); ok {
		_spec.AddField(currency.FieldAmountFactor, field.TypeInt64, value)
	}
	_node = &Currency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{currency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
