// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-base/rpc/ent/language"
)

// LanguageCreate is the builder for creating a Language entity.
type LanguageCreate struct {
	config
	mutation *LanguageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStatus sets the "status" field.
func (_c *LanguageCreate) SetStatus(v int64) *LanguageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LanguageCreate) SetNillableStatus(v *int64) *LanguageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortNo sets the "sort_no" field.
func (_c *LanguageCreate) SetSortNo(v int64) *LanguageCreate {
	_c.mutation.SetSortNo(v)
	return _c
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_c *LanguageCreate) SetNillableSortNo(v *int64) *LanguageCreate {
	if v != nil {
		_c.SetSortNo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LanguageCreate) SetCreatedAt(v time.Time) *LanguageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LanguageCreate) SetNillableCreatedAt(v *time.Time) *LanguageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LanguageCreate) SetUpdatedAt(v time.Time) *LanguageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LanguageCreate) SetNillableUpdatedAt(v *time.Time) *LanguageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *LanguageCreate) SetCode(v string) *LanguageCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNameI18n sets the "name_i18n" field.
func (_c *LanguageCreate) SetNameI18n(v map[string]string) *LanguageCreate {
	_c.mutation.SetNameI18n(v)
	return _c
}

// SetID sets the "id" field.
func (_c *LanguageCreate) SetID(v int64) *LanguageCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LanguageMutation object of the builder.
func (_c *LanguageCreate) Mutation() *LanguageMutation {
	return _c.mutation
}

// Save creates the Language in the database.
func (_c *LanguageCreate) Save(ctx context.Context) (*Language, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LanguageCreate) SaveX(ctx context.Context) *Language {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LanguageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LanguageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LanguageCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := language.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortNo(); !ok {
		v := language.DefaultSortNo
		_c.mutation.SetSortNo(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := language.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := language.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LanguageCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Language.status"`)}
	}
	if _, ok := _c.mutation.SortNo(); !ok {
		return &ValidationError{Name: "sort_no", err: errors.New(`ent: missing required field "Language.sort_no"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Language.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Language.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Language.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := language.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Language.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameI18n(); !ok {
		return &ValidationError{Name: "name_i18n", err: errors.New(`ent: missing required field "Language.name_i18n"`)}
	}
	return nil
}

func (_c *LanguageCreate) sqlSave(ctx context.Context) (*Language, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LanguageCreate) createSpec() (*Language, *sqlgraph.CreateSpec) {
	var (
		_node = &Language{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(language.Table, sqlgraph.NewFieldSpec(language.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(language.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortNo(); ok {
		_spec.SetField(language.FieldSortNo, field.TypeInt64, value)
		_node.SortNo = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(language.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(language.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(language.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.NameI18n(); ok {
		_spec.SetField(language.FieldNameI18n, field.TypeJSON, value)
		_node.NameI18n = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Language.Create().
//		SetStatus(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LanguageUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *LanguageCreate) OnConflict(opts ...sql.ConflictOption) *LanguageUpsertOne {
	_c.conflict = opts
	return &LanguageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Language.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LanguageCreate) OnConflictColumns(columns ...string) *LanguageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LanguageUpsertOne{
		create: _c,
	}
}

type (
	// LanguageUpsertOne is the builder for "upsert"-ing
	//  one Language node.
	LanguageUpsertOne struct {
		create *LanguageCreate
	}

	// LanguageUpsert is the "OnConflict" setter.
	LanguageUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *LanguageUpsert) SetStatus(v int64) *LanguageUpsert {
	u.Set(language.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LanguageUpsert) UpdateStatus() *LanguageUpsert {
	u.SetExcluded(language.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *LanguageUpsert) AddStatus(v int64) *LanguageUpsert {
	u.Add(language.FieldStatus, v)
	return u
}

// SetSortNo sets the "sort_no" field.
func (u *LanguageUpsert) SetSortNo(v int64) *LanguageUpsert {
	u.Set(language.FieldSortNo, v)
	return u
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *LanguageUpsert) UpdateSortNo() *LanguageUpsert {
	u.SetExcluded(language.FieldSortNo)
	return u
}

// AddSortNo adds v to the "sort_no" field.
func (u *LanguageUpsert) AddSortNo(v int64) *LanguageUpsert {
	u.Add(language.FieldSortNo, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LanguageUpsert) SetUpdatedAt(v time.Time) *LanguageUpsert {
	u.Set(language.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LanguageUpsert) UpdateUpdatedAt() *LanguageUpsert {
	u.SetExcluded(language.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *LanguageUpsert) SetCode(v string) *LanguageUpsert {
	u.Set(language.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *LanguageUpsert) UpdateCode() *LanguageUpsert {
	u.SetExcluded(language.FieldCode)
	return u
}

// SetNameI18n sets the "name_i18n" field.
func (u *LanguageUpsert) SetNameI18n(v map[string]string) *LanguageUpsert {
	u.Set(language.FieldNameI18n, v)
	return u
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *LanguageUpsert) UpdateNameI18n() *LanguageUpsert {
	u.SetExcluded(language.FieldNameI18n)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Language.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(language.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LanguageUpsertOne) UpdateNewValues() *LanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(language.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(language.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Language.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LanguageUpsertOne) Ignore() *LanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LanguageUpsertOne) DoNothing() *LanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LanguageCreate.OnConflict
// documentation for more info.
func (u *LanguageUpsertOne) Update(set func(*LanguageUpsert)) *LanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LanguageUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *LanguageUpsertOne) SetStatus(v int64) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *LanguageUpsertOne) AddStatus(v int64) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LanguageUpsertOne) UpdateStatus() *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateStatus()
	})
}

// SetSortNo sets the "sort_no" field.
func (u *LanguageUpsertOne) SetSortNo(v int64) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.SetSortNo(v)
	})
}

// AddSortNo adds v to the "sort_no" field.
func (u *LanguageUpsertOne) AddSortNo(v int64) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.AddSortNo(v)
	})
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *LanguageUpsertOne) UpdateSortNo() *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateSortNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LanguageUpsertOne) SetUpdatedAt(v time.Time) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LanguageUpsertOne) UpdateUpdatedAt() *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *LanguageUpsertOne) SetCode(v string) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *LanguageUpsertOne) UpdateCode() *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateCode()
	})
}

// SetNameI18n sets the "name_i18n" field.
func (u *LanguageUpsertOne) SetNameI18n(v map[string]string) *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.SetNameI18n(v)
	})
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *LanguageUpsertOne) UpdateNameI18n() *LanguageUpsertOne {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateNameI18n()
	})
}

// Exec executes the query.
func (u *LanguageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LanguageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LanguageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LanguageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LanguageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LanguageCreateBulk is the builder for creating many Language entities in bulk.
type LanguageCreateBulk struct {
	config
	err      error
	builders []*LanguageCreate
	conflict []sql.ConflictOption
}

// Save creates the Language entities in the database.
func (_c *LanguageCreateBulk) Save(ctx context.Context) ([]*Language, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Language, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LanguageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LanguageCreateBulk) SaveX(ctx context.Context) []*Language {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LanguageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LanguageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Language.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LanguageUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *LanguageCreateBulk) OnConflict(opts ...sql.ConflictOption) *LanguageUpsertBulk {
	_c.conflict = opts
	return &LanguageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Language.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LanguageCreateBulk) OnConflictColumns(columns ...string) *LanguageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LanguageUpsertBulk{
		create: _c,
	}
}

// LanguageUpsertBulk is the builder for "upsert"-ing
// a bulk of Language nodes.
type LanguageUpsertBulk struct {
	create *LanguageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Language.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(language.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LanguageUpsertBulk) UpdateNewValues() *LanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(language.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(language.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Language.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LanguageUpsertBulk) Ignore() *LanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LanguageUpsertBulk) DoNothing() *LanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LanguageCreateBulk.OnConflict
// documentation for more info.
func (u *LanguageUpsertBulk) Update(set func(*LanguageUpsert)) *LanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LanguageUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *LanguageUpsertBulk) SetStatus(v int64) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *LanguageUpsertBulk) AddStatus(v int64) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LanguageUpsertBulk) UpdateStatus() *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateStatus()
	})
}

// SetSortNo sets the "sort_no" field.
func (u *LanguageUpsertBulk) SetSortNo(v int64) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.SetSortNo(v)
	})
}

// AddSortNo adds v to the "sort_no" field.
func (u *LanguageUpsertBulk) AddSortNo(v int64) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.AddSortNo(v)
	})
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *LanguageUpsertBulk) UpdateSortNo() *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateSortNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LanguageUpsertBulk) SetUpdatedAt(v time.Time) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LanguageUpsertBulk) UpdateUpdatedAt() *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *LanguageUpsertBulk) SetCode(v string) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *LanguageUpsertBulk) UpdateCode() *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateCode()
	})
}

// SetNameI18n sets the "name_i18n" field.
func (u *LanguageUpsertBulk) SetNameI18n(v map[string]string) *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.SetNameI18n(v)
	})
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *LanguageUpsertBulk) UpdateNameI18n() *LanguageUpsertBulk {
	return u.Update(func(s *LanguageUpsert) {
		s.UpdateNameI18n()
	})
}

// Exec executes the query.
func (u *LanguageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LanguageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LanguageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LanguageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
