// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-base/rpc/ent/predicate"
	"oa.98ent.com/p9/platform-base/rpc/ent/region"
)

// RegionUpdate is the builder for updating Region entities.
type RegionUpdate struct {
	config
	hooks    []Hook
	mutation *RegionMutation
}

// Where appends a list predicates to the RegionUpdate builder.
func (_u *RegionUpdate) Where(ps ...predicate.Region) *RegionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RegionUpdate) SetStatus(v int64) *RegionUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableStatus(v *int64) *RegionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *RegionUpdate) AddStatus(v int64) *RegionUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *RegionUpdate) SetSortNo(v int64) *RegionUpdate {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableSortNo(v *int64) *RegionUpdate {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *RegionUpdate) AddSortNo(v int64) *RegionUpdate {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RegionUpdate) SetUpdatedAt(v time.Time) *RegionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *RegionUpdate) SetCode(v string) *RegionUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableCode(v *string) *RegionUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetCallingCode sets the "calling_code" field.
func (_u *RegionUpdate) SetCallingCode(v string) *RegionUpdate {
	_u.mutation.SetCallingCode(v)
	return _u
}

// SetNillableCallingCode sets the "calling_code" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableCallingCode(v *string) *RegionUpdate {
	if v != nil {
		_u.SetCallingCode(*v)
	}
	return _u
}

// SetNameI18n sets the "name_i18n" field.
func (_u *RegionUpdate) SetNameI18n(v map[string]string) *RegionUpdate {
	_u.mutation.SetNameI18n(v)
	return _u
}

// Mutation returns the RegionMutation object of the builder.
func (_u *RegionUpdate) Mutation() *RegionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RegionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RegionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RegionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := region.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := region.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Region.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := region.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Region.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CallingCode(); ok {
		if err := region.CallingCodeValidator(v); err != nil {
			return &ValidationError{Name: "calling_code", err: fmt.Errorf(`ent: validator failed for field "Region.calling_code": %w`, err)}
		}
	}
	return nil
}

func (_u *RegionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(region.Table, region.Columns, sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(region.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(region.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(region.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(region.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(region.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(region.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallingCode(); ok {
		_spec.SetField(region.FieldCallingCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameI18n(); ok {
		_spec.SetField(region.FieldNameI18n, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{region.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RegionUpdateOne is the builder for updating a single Region entity.
type RegionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegionMutation
}

// SetStatus sets the "status" field.
func (_u *RegionUpdateOne) SetStatus(v int64) *RegionUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableStatus(v *int64) *RegionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *RegionUpdateOne) AddStatus(v int64) *RegionUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *RegionUpdateOne) SetSortNo(v int64) *RegionUpdateOne {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableSortNo(v *int64) *RegionUpdateOne {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *RegionUpdateOne) AddSortNo(v int64) *RegionUpdateOne {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RegionUpdateOne) SetUpdatedAt(v time.Time) *RegionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *RegionUpdateOne) SetCode(v string) *RegionUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableCode(v *string) *RegionUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetCallingCode sets the "calling_code" field.
func (_u *RegionUpdateOne) SetCallingCode(v string) *RegionUpdateOne {
	_u.mutation.SetCallingCode(v)
	return _u
}

// SetNillableCallingCode sets the "calling_code" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableCallingCode(v *string) *RegionUpdateOne {
	if v != nil {
		_u.SetCallingCode(*v)
	}
	return _u
}

// SetNameI18n sets the "name_i18n" field.
func (_u *RegionUpdateOne) SetNameI18n(v map[string]string) *RegionUpdateOne {
	_u.mutation.SetNameI18n(v)
	return _u
}

// Mutation returns the RegionMutation object of the builder.
func (_u *RegionUpdateOne) Mutation() *RegionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RegionUpdate builder.
func (_u *RegionUpdateOne) Where(ps ...predicate.Region) *RegionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RegionUpdateOne) Select(field string, fields ...string) *RegionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Region entity.
func (_u *RegionUpdateOne) Save(ctx context.Context) (*Region, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegionUpdateOne) SaveX(ctx context.Context) *Region {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RegionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RegionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := region.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := region.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Region.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := region.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Region.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CallingCode(); ok {
		if err := region.CallingCodeValidator(v); err != nil {
			return &ValidationError{Name: "calling_code", err: fmt.Errorf(`ent: validator failed for field "Region.calling_code": %w`, err)}
		}
	}
	return nil
}

func (_u *RegionUpdateOne) sqlSave(ctx context.Context) (_node *Region, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(region.Table, region.Columns, sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Region.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, region.FieldID)
		for _, f := range fields {
			if !region.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != region.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(region.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(region.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(region.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(region.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(region.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(region.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallingCode(); ok {
		_spec.SetField(region.FieldCallingCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameI18n(); ok {
		_spec.SetField(region.FieldNameI18n, field.TypeJSON, value)
	}
	_node = &Region{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{region.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
