// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-base/rpc/ent/region"
)

// RegionCreate is the builder for creating a Region entity.
type RegionCreate struct {
	config
	mutation *RegionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStatus sets the "status" field.
func (_c *RegionCreate) SetStatus(v int64) *RegionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RegionCreate) SetNillableStatus(v *int64) *RegionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortNo sets the "sort_no" field.
func (_c *RegionCreate) SetSortNo(v int64) *RegionCreate {
	_c.mutation.SetSortNo(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RegionCreate) SetCreatedAt(v time.Time) *RegionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RegionCreate) SetNillableCreatedAt(v *time.Time) *RegionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RegionCreate) SetUpdatedAt(v time.Time) *RegionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RegionCreate) SetNillableUpdatedAt(v *time.Time) *RegionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *RegionCreate) SetCode(v string) *RegionCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetCallingCode sets the "calling_code" field.
func (_c *RegionCreate) SetCallingCode(v string) *RegionCreate {
	_c.mutation.SetCallingCode(v)
	return _c
}

// SetNameI18n sets the "name_i18n" field.
func (_c *RegionCreate) SetNameI18n(v map[string]string) *RegionCreate {
	_c.mutation.SetNameI18n(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RegionCreate) SetID(v int64) *RegionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RegionMutation object of the builder.
func (_c *RegionCreate) Mutation() *RegionMutation {
	return _c.mutation
}

// Save creates the Region in the database.
func (_c *RegionCreate) Save(ctx context.Context) (*Region, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RegionCreate) SaveX(ctx context.Context) *Region {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RegionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RegionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RegionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := region.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := region.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := region.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RegionCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Region.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := region.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Region.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortNo(); !ok {
		return &ValidationError{Name: "sort_no", err: errors.New(`ent: missing required field "Region.sort_no"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Region.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Region.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Region.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := region.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Region.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CallingCode(); !ok {
		return &ValidationError{Name: "calling_code", err: errors.New(`ent: missing required field "Region.calling_code"`)}
	}
	if v, ok := _c.mutation.CallingCode(); ok {
		if err := region.CallingCodeValidator(v); err != nil {
			return &ValidationError{Name: "calling_code", err: fmt.Errorf(`ent: validator failed for field "Region.calling_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameI18n(); !ok {
		return &ValidationError{Name: "name_i18n", err: errors.New(`ent: missing required field "Region.name_i18n"`)}
	}
	return nil
}

func (_c *RegionCreate) sqlSave(ctx context.Context) (*Region, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RegionCreate) createSpec() (*Region, *sqlgraph.CreateSpec) {
	var (
		_node = &Region{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(region.Table, sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(region.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortNo(); ok {
		_spec.SetField(region.FieldSortNo, field.TypeInt64, value)
		_node.SortNo = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(region.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(region.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(region.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.CallingCode(); ok {
		_spec.SetField(region.FieldCallingCode, field.TypeString, value)
		_node.CallingCode = value
	}
	if value, ok := _c.mutation.NameI18n(); ok {
		_spec.SetField(region.FieldNameI18n, field.TypeJSON, value)
		_node.NameI18n = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Region.Create().
//		SetStatus(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RegionUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *RegionCreate) OnConflict(opts ...sql.ConflictOption) *RegionUpsertOne {
	_c.conflict = opts
	return &RegionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Region.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RegionCreate) OnConflictColumns(columns ...string) *RegionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RegionUpsertOne{
		create: _c,
	}
}

type (
	// RegionUpsertOne is the builder for "upsert"-ing
	//  one Region node.
	RegionUpsertOne struct {
		create *RegionCreate
	}

	// RegionUpsert is the "OnConflict" setter.
	RegionUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *RegionUpsert) SetStatus(v int64) *RegionUpsert {
	u.Set(region.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RegionUpsert) UpdateStatus() *RegionUpsert {
	u.SetExcluded(region.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *RegionUpsert) AddStatus(v int64) *RegionUpsert {
	u.Add(region.FieldStatus, v)
	return u
}

// SetSortNo sets the "sort_no" field.
func (u *RegionUpsert) SetSortNo(v int64) *RegionUpsert {
	u.Set(region.FieldSortNo, v)
	return u
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *RegionUpsert) UpdateSortNo() *RegionUpsert {
	u.SetExcluded(region.FieldSortNo)
	return u
}

// AddSortNo adds v to the "sort_no" field.
func (u *RegionUpsert) AddSortNo(v int64) *RegionUpsert {
	u.Add(region.FieldSortNo, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RegionUpsert) SetUpdatedAt(v time.Time) *RegionUpsert {
	u.Set(region.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RegionUpsert) UpdateUpdatedAt() *RegionUpsert {
	u.SetExcluded(region.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *RegionUpsert) SetCode(v string) *RegionUpsert {
	u.Set(region.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RegionUpsert) UpdateCode() *RegionUpsert {
	u.SetExcluded(region.FieldCode)
	return u
}

// SetCallingCode sets the "calling_code" field.
func (u *RegionUpsert) SetCallingCode(v string) *RegionUpsert {
	u.Set(region.FieldCallingCode, v)
	return u
}

// UpdateCallingCode sets the "calling_code" field to the value that was provided on create.
func (u *RegionUpsert) UpdateCallingCode() *RegionUpsert {
	u.SetExcluded(region.FieldCallingCode)
	return u
}

// SetNameI18n sets the "name_i18n" field.
func (u *RegionUpsert) SetNameI18n(v map[string]string) *RegionUpsert {
	u.Set(region.FieldNameI18n, v)
	return u
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *RegionUpsert) UpdateNameI18n() *RegionUpsert {
	u.SetExcluded(region.FieldNameI18n)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Region.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(region.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RegionUpsertOne) UpdateNewValues() *RegionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(region.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(region.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Region.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RegionUpsertOne) Ignore() *RegionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RegionUpsertOne) DoNothing() *RegionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RegionCreate.OnConflict
// documentation for more info.
func (u *RegionUpsertOne) Update(set func(*RegionUpsert)) *RegionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RegionUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *RegionUpsertOne) SetStatus(v int64) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *RegionUpsertOne) AddStatus(v int64) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RegionUpsertOne) UpdateStatus() *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateStatus()
	})
}

// SetSortNo sets the "sort_no" field.
func (u *RegionUpsertOne) SetSortNo(v int64) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.SetSortNo(v)
	})
}

// AddSortNo adds v to the "sort_no" field.
func (u *RegionUpsertOne) AddSortNo(v int64) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.AddSortNo(v)
	})
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *RegionUpsertOne) UpdateSortNo() *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateSortNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RegionUpsertOne) SetUpdatedAt(v time.Time) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RegionUpsertOne) UpdateUpdatedAt() *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *RegionUpsertOne) SetCode(v string) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RegionUpsertOne) UpdateCode() *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateCode()
	})
}

// SetCallingCode sets the "calling_code" field.
func (u *RegionUpsertOne) SetCallingCode(v string) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.SetCallingCode(v)
	})
}

// UpdateCallingCode sets the "calling_code" field to the value that was provided on create.
func (u *RegionUpsertOne) UpdateCallingCode() *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateCallingCode()
	})
}

// SetNameI18n sets the "name_i18n" field.
func (u *RegionUpsertOne) SetNameI18n(v map[string]string) *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.SetNameI18n(v)
	})
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *RegionUpsertOne) UpdateNameI18n() *RegionUpsertOne {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateNameI18n()
	})
}

// Exec executes the query.
func (u *RegionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RegionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RegionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RegionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RegionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RegionCreateBulk is the builder for creating many Region entities in bulk.
type RegionCreateBulk struct {
	config
	err      error
	builders []*RegionCreate
	conflict []sql.ConflictOption
}

// Save creates the Region entities in the database.
func (_c *RegionCreateBulk) Save(ctx context.Context) ([]*Region, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Region, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RegionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RegionCreateBulk) SaveX(ctx context.Context) []*Region {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RegionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RegionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Region.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RegionUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *RegionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RegionUpsertBulk {
	_c.conflict = opts
	return &RegionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Region.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RegionCreateBulk) OnConflictColumns(columns ...string) *RegionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RegionUpsertBulk{
		create: _c,
	}
}

// RegionUpsertBulk is the builder for "upsert"-ing
// a bulk of Region nodes.
type RegionUpsertBulk struct {
	create *RegionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Region.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(region.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RegionUpsertBulk) UpdateNewValues() *RegionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(region.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(region.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Region.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RegionUpsertBulk) Ignore() *RegionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RegionUpsertBulk) DoNothing() *RegionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RegionCreateBulk.OnConflict
// documentation for more info.
func (u *RegionUpsertBulk) Update(set func(*RegionUpsert)) *RegionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RegionUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *RegionUpsertBulk) SetStatus(v int64) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *RegionUpsertBulk) AddStatus(v int64) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RegionUpsertBulk) UpdateStatus() *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateStatus()
	})
}

// SetSortNo sets the "sort_no" field.
func (u *RegionUpsertBulk) SetSortNo(v int64) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.SetSortNo(v)
	})
}

// AddSortNo adds v to the "sort_no" field.
func (u *RegionUpsertBulk) AddSortNo(v int64) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.AddSortNo(v)
	})
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *RegionUpsertBulk) UpdateSortNo() *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateSortNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RegionUpsertBulk) SetUpdatedAt(v time.Time) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RegionUpsertBulk) UpdateUpdatedAt() *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *RegionUpsertBulk) SetCode(v string) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RegionUpsertBulk) UpdateCode() *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateCode()
	})
}

// SetCallingCode sets the "calling_code" field.
func (u *RegionUpsertBulk) SetCallingCode(v string) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.SetCallingCode(v)
	})
}

// UpdateCallingCode sets the "calling_code" field to the value that was provided on create.
func (u *RegionUpsertBulk) UpdateCallingCode() *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateCallingCode()
	})
}

// SetNameI18n sets the "name_i18n" field.
func (u *RegionUpsertBulk) SetNameI18n(v map[string]string) *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.SetNameI18n(v)
	})
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *RegionUpsertBulk) UpdateNameI18n() *RegionUpsertBulk {
	return u.Update(func(s *RegionUpsert) {
		s.UpdateNameI18n()
	})
}

// Exec executes the query.
func (u *RegionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RegionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RegionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RegionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
