// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"oa.98ent.com/p9/platform-base/rpc/ent/currency"
	"oa.98ent.com/p9/platform-base/rpc/ent/language"
	"oa.98ent.com/p9/platform-base/rpc/ent/region"
	"oa.98ent.com/p9/platform-base/rpc/ent/schema"
	"oa.98ent.com/p9/platform-base/rpc/ent/timezone"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	currencyMixin := schema.Currency{}.Mixin()
	currencyMixinFields1 := currencyMixin[1].Fields()
	_ = currencyMixinFields1
	currencyMixinFields2 := currencyMixin[2].Fields()
	_ = currencyMixinFields2
	currencyMixinFields3 := currencyMixin[3].Fields()
	_ = currencyMixinFields3
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescStatus is the schema descriptor for status field.
	currencyDescStatus := currencyMixinFields1[0].Descriptor()
	// currency.DefaultStatus holds the default value on creation for the status field.
	currency.DefaultStatus = currencyDescStatus.Default.(int64)
	// currencyDescSortNo is the schema descriptor for sort_no field.
	currencyDescSortNo := currencyMixinFields2[0].Descriptor()
	// currency.DefaultSortNo holds the default value on creation for the sort_no field.
	currency.DefaultSortNo = currencyDescSortNo.Default.(int64)
	// currencyDescCreatedAt is the schema descriptor for created_at field.
	currencyDescCreatedAt := currencyMixinFields3[0].Descriptor()
	// currency.DefaultCreatedAt holds the default value on creation for the created_at field.
	currency.DefaultCreatedAt = currencyDescCreatedAt.Default.(func() time.Time)
	// currencyDescUpdatedAt is the schema descriptor for updated_at field.
	currencyDescUpdatedAt := currencyMixinFields3[1].Descriptor()
	// currency.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	currency.DefaultUpdatedAt = currencyDescUpdatedAt.Default.(func() time.Time)
	// currency.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	currency.UpdateDefaultUpdatedAt = currencyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// currencyDescCode is the schema descriptor for code field.
	currencyDescCode := currencyFields[0].Descriptor()
	// currency.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	currency.CodeValidator = currencyDescCode.Validators[0].(func(string) error)
	// currencyDescSymbol is the schema descriptor for symbol field.
	currencyDescSymbol := currencyFields[3].Descriptor()
	// currency.SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	currency.SymbolValidator = currencyDescSymbol.Validators[0].(func(string) error)
	languageMixin := schema.Language{}.Mixin()
	languageMixinFields1 := languageMixin[1].Fields()
	_ = languageMixinFields1
	languageMixinFields2 := languageMixin[2].Fields()
	_ = languageMixinFields2
	languageMixinFields3 := languageMixin[3].Fields()
	_ = languageMixinFields3
	languageFields := schema.Language{}.Fields()
	_ = languageFields
	// languageDescStatus is the schema descriptor for status field.
	languageDescStatus := languageMixinFields1[0].Descriptor()
	// language.DefaultStatus holds the default value on creation for the status field.
	language.DefaultStatus = languageDescStatus.Default.(int64)
	// languageDescSortNo is the schema descriptor for sort_no field.
	languageDescSortNo := languageMixinFields2[0].Descriptor()
	// language.DefaultSortNo holds the default value on creation for the sort_no field.
	language.DefaultSortNo = languageDescSortNo.Default.(int64)
	// languageDescCreatedAt is the schema descriptor for created_at field.
	languageDescCreatedAt := languageMixinFields3[0].Descriptor()
	// language.DefaultCreatedAt holds the default value on creation for the created_at field.
	language.DefaultCreatedAt = languageDescCreatedAt.Default.(func() time.Time)
	// languageDescUpdatedAt is the schema descriptor for updated_at field.
	languageDescUpdatedAt := languageMixinFields3[1].Descriptor()
	// language.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	language.DefaultUpdatedAt = languageDescUpdatedAt.Default.(func() time.Time)
	// language.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	language.UpdateDefaultUpdatedAt = languageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// languageDescCode is the schema descriptor for code field.
	languageDescCode := languageFields[0].Descriptor()
	// language.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	language.CodeValidator = languageDescCode.Validators[0].(func(string) error)
	regionMixin := schema.Region{}.Mixin()
	regionMixinFields1 := regionMixin[1].Fields()
	_ = regionMixinFields1
	regionMixinFields2 := regionMixin[2].Fields()
	_ = regionMixinFields2
	regionMixinFields3 := regionMixin[3].Fields()
	_ = regionMixinFields3
	regionFields := schema.Region{}.Fields()
	_ = regionFields
	// regionDescStatus is the schema descriptor for status field.
	regionDescStatus := regionMixinFields1[0].Descriptor()
	// region.DefaultStatus holds the default value on creation for the status field.
	region.DefaultStatus = regionDescStatus.Default.(int64)
	// regionDescSortNo is the schema descriptor for sort_no field.
	regionDescSortNo := regionMixinFields2[0].Descriptor()
	// region.DefaultSortNo holds the default value on creation for the sort_no field.
	region.DefaultSortNo = regionDescSortNo.Default.(int64)
	// regionDescCreatedAt is the schema descriptor for created_at field.
	regionDescCreatedAt := regionMixinFields3[0].Descriptor()
	// region.DefaultCreatedAt holds the default value on creation for the created_at field.
	region.DefaultCreatedAt = regionDescCreatedAt.Default.(func() time.Time)
	// regionDescUpdatedAt is the schema descriptor for updated_at field.
	regionDescUpdatedAt := regionMixinFields3[1].Descriptor()
	// region.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	region.DefaultUpdatedAt = regionDescUpdatedAt.Default.(func() time.Time)
	// region.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	region.UpdateDefaultUpdatedAt = regionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// regionDescCode is the schema descriptor for code field.
	regionDescCode := regionFields[0].Descriptor()
	// region.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	region.CodeValidator = regionDescCode.Validators[0].(func(string) error)
	// regionDescCallingCode is the schema descriptor for calling_code field.
	regionDescCallingCode := regionFields[1].Descriptor()
	// region.CallingCodeValidator is a validator for the "calling_code" field. It is called by the builders before save.
	region.CallingCodeValidator = regionDescCallingCode.Validators[0].(func(string) error)
	timezoneMixin := schema.Timezone{}.Mixin()
	timezoneMixinFields1 := timezoneMixin[1].Fields()
	_ = timezoneMixinFields1
	timezoneMixinFields2 := timezoneMixin[2].Fields()
	_ = timezoneMixinFields2
	timezoneMixinFields3 := timezoneMixin[3].Fields()
	_ = timezoneMixinFields3
	timezoneFields := schema.Timezone{}.Fields()
	_ = timezoneFields
	// timezoneDescStatus is the schema descriptor for status field.
	timezoneDescStatus := timezoneMixinFields1[0].Descriptor()
	// timezone.DefaultStatus holds the default value on creation for the status field.
	timezone.DefaultStatus = timezoneDescStatus.Default.(int64)
	// timezoneDescSortNo is the schema descriptor for sort_no field.
	timezoneDescSortNo := timezoneMixinFields2[0].Descriptor()
	// timezone.DefaultSortNo holds the default value on creation for the sort_no field.
	timezone.DefaultSortNo = timezoneDescSortNo.Default.(int64)
	// timezoneDescCreatedAt is the schema descriptor for created_at field.
	timezoneDescCreatedAt := timezoneMixinFields3[0].Descriptor()
	// timezone.DefaultCreatedAt holds the default value on creation for the created_at field.
	timezone.DefaultCreatedAt = timezoneDescCreatedAt.Default.(func() time.Time)
	// timezoneDescUpdatedAt is the schema descriptor for updated_at field.
	timezoneDescUpdatedAt := timezoneMixinFields3[1].Descriptor()
	// timezone.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timezone.DefaultUpdatedAt = timezoneDescUpdatedAt.Default.(func() time.Time)
	// timezone.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	timezone.UpdateDefaultUpdatedAt = timezoneDescUpdatedAt.UpdateDefault.(func() time.Time)
	// timezoneDescCode is the schema descriptor for code field.
	timezoneDescCode := timezoneFields[0].Descriptor()
	// timezone.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	timezone.CodeValidator = timezoneDescCode.Validators[0].(func(string) error)
}
