// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-base/rpc/ent/timezone"
)

// TimezoneCreate is the builder for creating a Timezone entity.
type TimezoneCreate struct {
	config
	mutation *TimezoneMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStatus sets the "status" field.
func (_c *TimezoneCreate) SetStatus(v int64) *TimezoneCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TimezoneCreate) SetNillableStatus(v *int64) *TimezoneCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortNo sets the "sort_no" field.
func (_c *TimezoneCreate) SetSortNo(v int64) *TimezoneCreate {
	_c.mutation.SetSortNo(v)
	return _c
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_c *TimezoneCreate) SetNillableSortNo(v *int64) *TimezoneCreate {
	if v != nil {
		_c.SetSortNo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TimezoneCreate) SetCreatedAt(v time.Time) *TimezoneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TimezoneCreate) SetNillableCreatedAt(v *time.Time) *TimezoneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TimezoneCreate) SetUpdatedAt(v time.Time) *TimezoneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TimezoneCreate) SetNillableUpdatedAt(v *time.Time) *TimezoneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *TimezoneCreate) SetCode(v string) *TimezoneCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNameI18n sets the "name_i18n" field.
func (_c *TimezoneCreate) SetNameI18n(v map[string]string) *TimezoneCreate {
	_c.mutation.SetNameI18n(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TimezoneCreate) SetID(v int64) *TimezoneCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TimezoneMutation object of the builder.
func (_c *TimezoneCreate) Mutation() *TimezoneMutation {
	return _c.mutation
}

// Save creates the Timezone in the database.
func (_c *TimezoneCreate) Save(ctx context.Context) (*Timezone, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimezoneCreate) SaveX(ctx context.Context) *Timezone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimezoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimezoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TimezoneCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := timezone.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortNo(); !ok {
		v := timezone.DefaultSortNo
		_c.mutation.SetSortNo(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := timezone.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := timezone.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimezoneCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Timezone.status"`)}
	}
	if _, ok := _c.mutation.SortNo(); !ok {
		return &ValidationError{Name: "sort_no", err: errors.New(`ent: missing required field "Timezone.sort_no"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Timezone.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Timezone.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Timezone.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := timezone.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Timezone.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameI18n(); !ok {
		return &ValidationError{Name: "name_i18n", err: errors.New(`ent: missing required field "Timezone.name_i18n"`)}
	}
	return nil
}

func (_c *TimezoneCreate) sqlSave(ctx context.Context) (*Timezone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimezoneCreate) createSpec() (*Timezone, *sqlgraph.CreateSpec) {
	var (
		_node = &Timezone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timezone.Table, sqlgraph.NewFieldSpec(timezone.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(timezone.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortNo(); ok {
		_spec.SetField(timezone.FieldSortNo, field.TypeInt64, value)
		_node.SortNo = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(timezone.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(timezone.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(timezone.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.NameI18n(); ok {
		_spec.SetField(timezone.FieldNameI18n, field.TypeJSON, value)
		_node.NameI18n = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Timezone.Create().
//		SetStatus(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TimezoneUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *TimezoneCreate) OnConflict(opts ...sql.ConflictOption) *TimezoneUpsertOne {
	_c.conflict = opts
	return &TimezoneUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Timezone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TimezoneCreate) OnConflictColumns(columns ...string) *TimezoneUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TimezoneUpsertOne{
		create: _c,
	}
}

type (
	// TimezoneUpsertOne is the builder for "upsert"-ing
	//  one Timezone node.
	TimezoneUpsertOne struct {
		create *TimezoneCreate
	}

	// TimezoneUpsert is the "OnConflict" setter.
	TimezoneUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *TimezoneUpsert) SetStatus(v int64) *TimezoneUpsert {
	u.Set(timezone.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TimezoneUpsert) UpdateStatus() *TimezoneUpsert {
	u.SetExcluded(timezone.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *TimezoneUpsert) AddStatus(v int64) *TimezoneUpsert {
	u.Add(timezone.FieldStatus, v)
	return u
}

// SetSortNo sets the "sort_no" field.
func (u *TimezoneUpsert) SetSortNo(v int64) *TimezoneUpsert {
	u.Set(timezone.FieldSortNo, v)
	return u
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *TimezoneUpsert) UpdateSortNo() *TimezoneUpsert {
	u.SetExcluded(timezone.FieldSortNo)
	return u
}

// AddSortNo adds v to the "sort_no" field.
func (u *TimezoneUpsert) AddSortNo(v int64) *TimezoneUpsert {
	u.Add(timezone.FieldSortNo, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TimezoneUpsert) SetUpdatedAt(v time.Time) *TimezoneUpsert {
	u.Set(timezone.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TimezoneUpsert) UpdateUpdatedAt() *TimezoneUpsert {
	u.SetExcluded(timezone.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *TimezoneUpsert) SetCode(v string) *TimezoneUpsert {
	u.Set(timezone.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TimezoneUpsert) UpdateCode() *TimezoneUpsert {
	u.SetExcluded(timezone.FieldCode)
	return u
}

// SetNameI18n sets the "name_i18n" field.
func (u *TimezoneUpsert) SetNameI18n(v map[string]string) *TimezoneUpsert {
	u.Set(timezone.FieldNameI18n, v)
	return u
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *TimezoneUpsert) UpdateNameI18n() *TimezoneUpsert {
	u.SetExcluded(timezone.FieldNameI18n)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Timezone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(timezone.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TimezoneUpsertOne) UpdateNewValues() *TimezoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(timezone.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(timezone.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Timezone.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TimezoneUpsertOne) Ignore() *TimezoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TimezoneUpsertOne) DoNothing() *TimezoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TimezoneCreate.OnConflict
// documentation for more info.
func (u *TimezoneUpsertOne) Update(set func(*TimezoneUpsert)) *TimezoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TimezoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *TimezoneUpsertOne) SetStatus(v int64) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *TimezoneUpsertOne) AddStatus(v int64) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TimezoneUpsertOne) UpdateStatus() *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateStatus()
	})
}

// SetSortNo sets the "sort_no" field.
func (u *TimezoneUpsertOne) SetSortNo(v int64) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetSortNo(v)
	})
}

// AddSortNo adds v to the "sort_no" field.
func (u *TimezoneUpsertOne) AddSortNo(v int64) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.AddSortNo(v)
	})
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *TimezoneUpsertOne) UpdateSortNo() *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateSortNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TimezoneUpsertOne) SetUpdatedAt(v time.Time) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TimezoneUpsertOne) UpdateUpdatedAt() *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *TimezoneUpsertOne) SetCode(v string) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TimezoneUpsertOne) UpdateCode() *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateCode()
	})
}

// SetNameI18n sets the "name_i18n" field.
func (u *TimezoneUpsertOne) SetNameI18n(v map[string]string) *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetNameI18n(v)
	})
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *TimezoneUpsertOne) UpdateNameI18n() *TimezoneUpsertOne {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateNameI18n()
	})
}

// Exec executes the query.
func (u *TimezoneUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TimezoneCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TimezoneUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TimezoneUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TimezoneUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TimezoneCreateBulk is the builder for creating many Timezone entities in bulk.
type TimezoneCreateBulk struct {
	config
	err      error
	builders []*TimezoneCreate
	conflict []sql.ConflictOption
}

// Save creates the Timezone entities in the database.
func (_c *TimezoneCreateBulk) Save(ctx context.Context) ([]*Timezone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Timezone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimezoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimezoneCreateBulk) SaveX(ctx context.Context) []*Timezone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimezoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimezoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Timezone.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TimezoneUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *TimezoneCreateBulk) OnConflict(opts ...sql.ConflictOption) *TimezoneUpsertBulk {
	_c.conflict = opts
	return &TimezoneUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Timezone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TimezoneCreateBulk) OnConflictColumns(columns ...string) *TimezoneUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TimezoneUpsertBulk{
		create: _c,
	}
}

// TimezoneUpsertBulk is the builder for "upsert"-ing
// a bulk of Timezone nodes.
type TimezoneUpsertBulk struct {
	create *TimezoneCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Timezone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(timezone.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TimezoneUpsertBulk) UpdateNewValues() *TimezoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(timezone.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(timezone.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Timezone.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TimezoneUpsertBulk) Ignore() *TimezoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TimezoneUpsertBulk) DoNothing() *TimezoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TimezoneCreateBulk.OnConflict
// documentation for more info.
func (u *TimezoneUpsertBulk) Update(set func(*TimezoneUpsert)) *TimezoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TimezoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *TimezoneUpsertBulk) SetStatus(v int64) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *TimezoneUpsertBulk) AddStatus(v int64) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TimezoneUpsertBulk) UpdateStatus() *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateStatus()
	})
}

// SetSortNo sets the "sort_no" field.
func (u *TimezoneUpsertBulk) SetSortNo(v int64) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetSortNo(v)
	})
}

// AddSortNo adds v to the "sort_no" field.
func (u *TimezoneUpsertBulk) AddSortNo(v int64) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.AddSortNo(v)
	})
}

// UpdateSortNo sets the "sort_no" field to the value that was provided on create.
func (u *TimezoneUpsertBulk) UpdateSortNo() *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateSortNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TimezoneUpsertBulk) SetUpdatedAt(v time.Time) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TimezoneUpsertBulk) UpdateUpdatedAt() *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *TimezoneUpsertBulk) SetCode(v string) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TimezoneUpsertBulk) UpdateCode() *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateCode()
	})
}

// SetNameI18n sets the "name_i18n" field.
func (u *TimezoneUpsertBulk) SetNameI18n(v map[string]string) *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.SetNameI18n(v)
	})
}

// UpdateNameI18n sets the "name_i18n" field to the value that was provided on create.
func (u *TimezoneUpsertBulk) UpdateNameI18n() *TimezoneUpsertBulk {
	return u.Update(func(s *TimezoneUpsert) {
		s.UpdateNameI18n()
	})
}

// Exec executes the query.
func (u *TimezoneUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TimezoneCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TimezoneCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TimezoneUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
