// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/platform-base/rpc/ent/timezone"
)

// 系统时区表
type Timezone struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 状态: 1启用, 2停用
	Status int64 `json:"status,omitempty"`
	// 排序值, 数值越小越靠前
	SortNo int64 `json:"sort_no,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// IANA 时区编码
	Code string `json:"code,omitempty"`
	// 多语言名称
	NameI18n     map[string]string `json:"name_i18n,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Timezone) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timezone.FieldNameI18n:
			values[i] = new([]byte)
		case timezone.FieldID, timezone.FieldStatus, timezone.FieldSortNo:
			values[i] = new(sql.NullInt64)
		case timezone.FieldCode:
			values[i] = new(sql.NullString)
		case timezone.FieldCreatedAt, timezone.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Timezone fields.
func (_m *Timezone) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timezone.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case timezone.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.Int64
			}
		case timezone.FieldSortNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_no", values[i])
			} else if value.Valid {
				_m.SortNo = value.Int64
			}
		case timezone.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case timezone.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case timezone.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case timezone.FieldNameI18n:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field name_i18n", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NameI18n); err != nil {
					return fmt.Errorf("unmarshal field name_i18n: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Timezone.
// This includes values selected through modifiers, order, etc.
func (_m *Timezone) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Timezone.
// Note that you need to call Timezone.Unwrap() before calling this method if this Timezone
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Timezone) Update() *TimezoneUpdateOne {
	return NewTimezoneClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Timezone entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Timezone) Unwrap() *Timezone {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Timezone is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Timezone) String() string {
	var builder strings.Builder
	builder.WriteString("Timezone(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("sort_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortNo))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name_i18n=")
	builder.WriteString(fmt.Sprintf("%v", _m.NameI18n))
	builder.WriteByte(')')
	return builder.String()
}

// Timezones is a parsable slice of Timezone.
type Timezones []*Timezone
