// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package languageservice

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/pb/base"

	"oa.98ent.com/p9/platform-base/rpc/pb/base/language"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LanguageService interface {
		// 创建语言
		Create(ctx context.Context, in *language.CreateLanguageRequest, opts ...grpc.CallOption) (*language.CreateLanguageResponse, error)
		// 修改语言
		Update(ctx context.Context, in *language.UpdateLanguageRequest, opts ...grpc.CallOption) (*language.UpdateLanguageResponse, error)
		// 获取语言
		Get(ctx context.Context, in *language.GetLanguageRequest, opts ...grpc.CallOption) (*language.GetLanguageResponse, error)
		// 获取语言管理列表
		List(ctx context.Context, in *language.ListLanguagesRequest, opts ...grpc.CallOption) (*language.ListLanguagesResponse, error)
		// 获取全部语言
		ListAll(ctx context.Context, in *language.ListAllLanguagesRequest, opts ...grpc.CallOption) (*language.ListAllLanguagesResponse, error)
		// 调整语言排序
		Reorder(ctx context.Context, in *language.ReorderLanguageRequest, opts ...grpc.CallOption) (*language.ReorderLanguageResponse, error)
	}

	defaultLanguageService struct {
		cli zrpc.Client
	}
)

func NewLanguageService(cli zrpc.Client) LanguageService {
	return &defaultLanguageService{
		cli: cli,
	}
}

// 创建语言
func (m *defaultLanguageService) Create(ctx context.Context, in *language.CreateLanguageRequest, opts ...grpc.CallOption) (*language.CreateLanguageResponse, error) {
	client := base.NewLanguageServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 修改语言
func (m *defaultLanguageService) Update(ctx context.Context, in *language.UpdateLanguageRequest, opts ...grpc.CallOption) (*language.UpdateLanguageResponse, error) {
	client := base.NewLanguageServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 获取语言
func (m *defaultLanguageService) Get(ctx context.Context, in *language.GetLanguageRequest, opts ...grpc.CallOption) (*language.GetLanguageResponse, error) {
	client := base.NewLanguageServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 获取语言管理列表
func (m *defaultLanguageService) List(ctx context.Context, in *language.ListLanguagesRequest, opts ...grpc.CallOption) (*language.ListLanguagesResponse, error) {
	client := base.NewLanguageServiceClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 获取全部语言
func (m *defaultLanguageService) ListAll(ctx context.Context, in *language.ListAllLanguagesRequest, opts ...grpc.CallOption) (*language.ListAllLanguagesResponse, error) {
	client := base.NewLanguageServiceClient(m.cli.Conn())
	return client.ListAll(ctx, in, opts...)
}

// 调整语言排序
func (m *defaultLanguageService) Reorder(ctx context.Context, in *language.ReorderLanguageRequest, opts ...grpc.CallOption) (*language.ReorderLanguageResponse, error) {
	client := base.NewLanguageServiceClient(m.cli.Conn())
	return client.Reorder(ctx, in, opts...)
}
