// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CurrencyColumns holds the columns for the "currency" table.
	CurrencyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID", SchemaType: map[string]string{"postgres": "bigint"}},
		{Name: "status", Type: field.TypeInt64, Comment: "状态: 1启用, 2停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort_no", Type: field.TypeInt64, Comment: "排序值, 数值越小越靠前", Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 16, Comment: "货币编码"},
		{Name: "name_i18n", Type: field.TypeJSON, Comment: "多语言名称", SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "currency_type", Type: field.TypeInt64, Comment: "货币类型: 1法定货币, 2虚拟货币", SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "symbol", Type: field.TypeString, Size: 16, Comment: "货币符号"},
		{Name: "amount_factor", Type: field.TypeInt64, Comment: "金额换算倍率, 例如 USD 为100, VND为1", SchemaType: map[string]string{"postgres": "bigint"}},
	}
	// CurrencyTable holds the schema information for the "currency" table.
	CurrencyTable = &schema.Table{
		Name:       "currency",
		Comment:    "系统货币表",
		Columns:    CurrencyColumns,
		PrimaryKey: []*schema.Column{CurrencyColumns[0]},
	}
	// LanguageColumns holds the columns for the "language" table.
	LanguageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID", SchemaType: map[string]string{"postgres": "bigint"}},
		{Name: "status", Type: field.TypeInt64, Comment: "状态: 1启用, 2停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort_no", Type: field.TypeInt64, Comment: "排序值, 数值越小越靠前", Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 35, Comment: "语言编码"},
		{Name: "name_i18n", Type: field.TypeJSON, Comment: "多语言名称", SchemaType: map[string]string{"postgres": "jsonb"}},
	}
	// LanguageTable holds the schema information for the "language" table.
	LanguageTable = &schema.Table{
		Name:       "language",
		Comment:    "系统语言表",
		Columns:    LanguageColumns,
		PrimaryKey: []*schema.Column{LanguageColumns[0]},
	}
	// RegionColumns holds the columns for the "region" table.
	RegionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID", SchemaType: map[string]string{"postgres": "bigint"}},
		{Name: "status", Type: field.TypeInt64, Comment: "状态: 1启用, 2停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort_no", Type: field.TypeInt64, Comment: "排序值, 数值越小越靠前", Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 2, Comment: "国家或地区编码"},
		{Name: "calling_code", Type: field.TypeString, Size: 3, Comment: "国际电话区号, 不包含加号"},
		{Name: "name_i18n", Type: field.TypeJSON, Comment: "多语言名称", SchemaType: map[string]string{"postgres": "jsonb"}},
	}
	// RegionTable holds the schema information for the "region" table.
	RegionTable = &schema.Table{
		Name:       "region",
		Comment:    "系统国家地区表",
		Columns:    RegionColumns,
		PrimaryKey: []*schema.Column{RegionColumns[0]},
	}
	// TimezoneColumns holds the columns for the "timezone" table.
	TimezoneColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID", SchemaType: map[string]string{"postgres": "bigint"}},
		{Name: "status", Type: field.TypeInt64, Comment: "状态: 1启用, 2停用", Default: 1, SchemaType: map[string]string{"postgres": "smallint"}},
		{Name: "sort_no", Type: field.TypeInt64, Comment: "排序值, 数值越小越靠前", Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间", SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64, Comment: "IANA 时区编码"},
		{Name: "name_i18n", Type: field.TypeJSON, Comment: "多语言名称", SchemaType: map[string]string{"postgres": "jsonb"}},
	}
	// TimezoneTable holds the schema information for the "timezone" table.
	TimezoneTable = &schema.Table{
		Name:       "timezone",
		Comment:    "系统时区表",
		Columns:    TimezoneColumns,
		PrimaryKey: []*schema.Column{TimezoneColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CurrencyTable,
		LanguageTable,
		RegionTable,
		TimezoneTable,
	}
)

func init() {
	CurrencyTable.Annotation = &entsql.Annotation{
		Table: "currency",
	}
	LanguageTable.Annotation = &entsql.Annotation{
		Table: "language",
	}
	RegionTable.Annotation = &entsql.Annotation{
		Table: "region",
	}
	TimezoneTable.Annotation = &entsql.Annotation{
		Table: "timezone",
	}
}
