// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: types/region.proto

package region

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 国家地区信息
type RegionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家或地区ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 国家或地区编码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 国际电话区号, 不包含加号
	CallingCode string `protobuf:"bytes,3,opt,name=calling_code,json=callingCode,proto3" json:"calling_code,omitempty"`
	// 多语言名称
	NameI18N map[string]string `protobuf:"bytes,4,rep,name=name_i18n,json=nameI18n,proto3" json:"name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 状态: 1启用, 2停用
	Status int64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 排序值, 数值越小越靠前
	SortNo        int64 `protobuf:"varint,6,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	mi := &file_types_region_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{0}
}

func (x *RegionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegionInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegionInfo) GetCallingCode() string {
	if x != nil {
		return x.CallingCode
	}
	return ""
}

func (x *RegionInfo) GetNameI18N() map[string]string {
	if x != nil {
		return x.NameI18N
	}
	return nil
}

func (x *RegionInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RegionInfo) GetSortNo() int64 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

// 创建国家地区请求
type CreateRegionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家或地区编码
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 国际电话区号, 不包含加号
	CallingCode string `protobuf:"bytes,2,opt,name=calling_code,json=callingCode,proto3" json:"calling_code,omitempty"`
	// 多语言名称
	NameI18N map[string]string `protobuf:"bytes,3,rep,name=name_i18n,json=nameI18n,proto3" json:"name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionRequest) Reset() {
	*x = CreateRegionRequest{}
	mi := &file_types_region_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionRequest) ProtoMessage() {}

func (x *CreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRegionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRegionRequest) GetCallingCode() string {
	if x != nil {
		return x.CallingCode
	}
	return ""
}

func (x *CreateRegionRequest) GetNameI18N() map[string]string {
	if x != nil {
		return x.NameI18N
	}
	return nil
}

func (x *CreateRegionRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 创建国家地区响应
type CreateRegionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家或地区ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionResponse) Reset() {
	*x = CreateRegionResponse{}
	mi := &file_types_region_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionResponse) ProtoMessage() {}

func (x *CreateRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionResponse.ProtoReflect.Descriptor instead.
func (*CreateRegionResponse) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRegionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改国家地区请求
type UpdateRegionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家或地区ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 国际电话区号, 不传时不修改
	CallingCode *string `protobuf:"bytes,2,opt,name=calling_code,json=callingCode,proto3,oneof" json:"calling_code,omitempty"`
	// 多语言名称, 为空时不修改
	NameI18N map[string]string `protobuf:"bytes,3,rep,name=name_i18n,json=nameI18n,proto3" json:"name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegionRequest) Reset() {
	*x = UpdateRegionRequest{}
	mi := &file_types_region_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegionRequest) ProtoMessage() {}

func (x *UpdateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegionRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegionRequest) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRegionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRegionRequest) GetCallingCode() string {
	if x != nil && x.CallingCode != nil {
		return *x.CallingCode
	}
	return ""
}

func (x *UpdateRegionRequest) GetNameI18N() map[string]string {
	if x != nil {
		return x.NameI18N
	}
	return nil
}

func (x *UpdateRegionRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 修改国家地区响应
type UpdateRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegionResponse) Reset() {
	*x = UpdateRegionResponse{}
	mi := &file_types_region_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegionResponse) ProtoMessage() {}

func (x *UpdateRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegionResponse.ProtoReflect.Descriptor instead.
func (*UpdateRegionResponse) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{4}
}

// 获取国家地区请求
type GetRegionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家或地区ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionRequest) Reset() {
	*x = GetRegionRequest{}
	mi := &file_types_region_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionRequest) ProtoMessage() {}

func (x *GetRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionRequest.ProtoReflect.Descriptor instead.
func (*GetRegionRequest) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{5}
}

func (x *GetRegionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取国家地区响应
type GetRegionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家地区信息
	Region        *RegionInfo `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionResponse) Reset() {
	*x = GetRegionResponse{}
	mi := &file_types_region_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionResponse) ProtoMessage() {}

func (x *GetRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionResponse.ProtoReflect.Descriptor instead.
func (*GetRegionResponse) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{6}
}

func (x *GetRegionResponse) GetRegion() *RegionInfo {
	if x != nil {
		return x.Region
	}
	return nil
}

// 获取国家地区管理列表请求
type ListRegionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码, 从1开始
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsRequest) Reset() {
	*x = ListRegionsRequest{}
	mi := &file_types_region_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsRequest) ProtoMessage() {}

func (x *ListRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsRequest.ProtoReflect.Descriptor instead.
func (*ListRegionsRequest) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{7}
}

func (x *ListRegionsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRegionsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRegionsRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取国家地区管理列表响应
type ListRegionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 国家地区列表
	List          []*RegionInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsResponse) Reset() {
	*x = ListRegionsResponse{}
	mi := &file_types_region_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsResponse) ProtoMessage() {}

func (x *ListRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsResponse.ProtoReflect.Descriptor instead.
func (*ListRegionsResponse) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{8}
}

func (x *ListRegionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRegionsResponse) GetList() []*RegionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取全部国家地区请求
type ListAllRegionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllRegionsRequest) Reset() {
	*x = ListAllRegionsRequest{}
	mi := &file_types_region_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllRegionsRequest) ProtoMessage() {}

func (x *ListAllRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllRegionsRequest.ProtoReflect.Descriptor instead.
func (*ListAllRegionsRequest) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllRegionsRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取全部国家地区响应
type ListAllRegionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 国家地区列表
	List          []*RegionInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllRegionsResponse) Reset() {
	*x = ListAllRegionsResponse{}
	mi := &file_types_region_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllRegionsResponse) ProtoMessage() {}

func (x *ListAllRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllRegionsResponse.ProtoReflect.Descriptor instead.
func (*ListAllRegionsResponse) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{10}
}

func (x *ListAllRegionsResponse) GetList() []*RegionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 调整国家地区排序请求
type ReorderRegionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 需要移动的国家地区ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 目标国家地区ID
	TargetId      int64 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRegionRequest) Reset() {
	*x = ReorderRegionRequest{}
	mi := &file_types_region_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRegionRequest) ProtoMessage() {}

func (x *ReorderRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRegionRequest.ProtoReflect.Descriptor instead.
func (*ReorderRegionRequest) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{11}
}

func (x *ReorderRegionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReorderRegionRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 调整国家地区排序响应
type ReorderRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRegionResponse) Reset() {
	*x = ReorderRegionResponse{}
	mi := &file_types_region_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRegionResponse) ProtoMessage() {}

func (x *ReorderRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_region_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRegionResponse.ProtoReflect.Descriptor instead.
func (*ReorderRegionResponse) Descriptor() ([]byte, []int) {
	return file_types_region_proto_rawDescGZIP(), []int{12}
}

var File_types_region_proto protoreflect.FileDescriptor

const file_types_region_proto_rawDesc = "" +
	"\n" +
	"\x12types/region.proto\x12\x06region\"\x80\x02\n" +
	"\n" +
	"RegionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fcalling_code\x18\x03 \x01(\tR\vcallingCode\x12=\n" +
	"\tname_i18n\x18\x04 \x03(\v2 .region.RegionInfo.NameI18nEntryR\bnameI18n\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x17\n" +
	"\asort_no\x18\x06 \x01(\x03R\x06sortNo\x1a;\n" +
	"\rNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x13CreateRegionRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fcalling_code\x18\x02 \x01(\tR\vcallingCode\x12F\n" +
	"\tname_i18n\x18\x03 \x03(\v2).region.CreateRegionRequest.NameI18nEntryR\bnameI18n\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x03H\x00R\x06status\x88\x01\x01\x1a;\n" +
	"\rNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_status\"&\n" +
	"\x14CreateRegionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8b\x02\n" +
	"\x13UpdateRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\fcalling_code\x18\x02 \x01(\tH\x00R\vcallingCode\x88\x01\x01\x12F\n" +
	"\tname_i18n\x18\x03 \x03(\v2).region.UpdateRegionRequest.NameI18nEntryR\bnameI18n\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x03H\x01R\x06status\x88\x01\x01\x1a;\n" +
	"\rNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_calling_codeB\t\n" +
	"\a_status\"\x16\n" +
	"\x14UpdateRegionResponse\"\"\n" +
	"\x10GetRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x11GetRegionResponse\x12*\n" +
	"\x06region\x18\x01 \x01(\v2\x12.region.RegionInfoR\x06region\"m\n" +
	"\x12ListRegionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x03H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"S\n" +
	"\x13ListRegionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.region.RegionInfoR\x04list\"?\n" +
	"\x15ListAllRegionsRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x03H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"@\n" +
	"\x16ListAllRegionsResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.region.RegionInfoR\x04list\"C\n" +
	"\x14ReorderRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\"\x17\n" +
	"\x15ReorderRegionResponseB2Z0oa.98ent.com/p9/platform-base/rpc/pb/base/regionb\x06proto3"

var (
	file_types_region_proto_rawDescOnce sync.Once
	file_types_region_proto_rawDescData []byte
)

func file_types_region_proto_rawDescGZIP() []byte {
	file_types_region_proto_rawDescOnce.Do(func() {
		file_types_region_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_region_proto_rawDesc), len(file_types_region_proto_rawDesc)))
	})
	return file_types_region_proto_rawDescData
}

var file_types_region_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_types_region_proto_goTypes = []any{
	(*RegionInfo)(nil),             // 0: region.RegionInfo
	(*CreateRegionRequest)(nil),    // 1: region.CreateRegionRequest
	(*CreateRegionResponse)(nil),   // 2: region.CreateRegionResponse
	(*UpdateRegionRequest)(nil),    // 3: region.UpdateRegionRequest
	(*UpdateRegionResponse)(nil),   // 4: region.UpdateRegionResponse
	(*GetRegionRequest)(nil),       // 5: region.GetRegionRequest
	(*GetRegionResponse)(nil),      // 6: region.GetRegionResponse
	(*ListRegionsRequest)(nil),     // 7: region.ListRegionsRequest
	(*ListRegionsResponse)(nil),    // 8: region.ListRegionsResponse
	(*ListAllRegionsRequest)(nil),  // 9: region.ListAllRegionsRequest
	(*ListAllRegionsResponse)(nil), // 10: region.ListAllRegionsResponse
	(*ReorderRegionRequest)(nil),   // 11: region.ReorderRegionRequest
	(*ReorderRegionResponse)(nil),  // 12: region.ReorderRegionResponse
	nil,                            // 13: region.RegionInfo.NameI18nEntry
	nil,                            // 14: region.CreateRegionRequest.NameI18nEntry
	nil,                            // 15: region.UpdateRegionRequest.NameI18nEntry
}
var file_types_region_proto_depIdxs = []int32{
	13, // 0: region.RegionInfo.name_i18n:type_name -> region.RegionInfo.NameI18nEntry
	14, // 1: region.CreateRegionRequest.name_i18n:type_name -> region.CreateRegionRequest.NameI18nEntry
	15, // 2: region.UpdateRegionRequest.name_i18n:type_name -> region.UpdateRegionRequest.NameI18nEntry
	0,  // 3: region.GetRegionResponse.region:type_name -> region.RegionInfo
	0,  // 4: region.ListRegionsResponse.list:type_name -> region.RegionInfo
	0,  // 5: region.ListAllRegionsResponse.list:type_name -> region.RegionInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_types_region_proto_init() }
func file_types_region_proto_init() {
	if File_types_region_proto != nil {
		return
	}
	file_types_region_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_region_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_region_proto_msgTypes[7].OneofWrappers = []any{}
	file_types_region_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_region_proto_rawDesc), len(file_types_region_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_region_proto_goTypes,
		DependencyIndexes: file_types_region_proto_depIdxs,
		MessageInfos:      file_types_region_proto_msgTypes,
	}.Build()
	File_types_region_proto = out.File
	file_types_region_proto_goTypes = nil
	file_types_region_proto_depIdxs = nil
}
