// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Currency is the predicate function for currency builders.
type Currency func(*sql.Selector)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)

// Region is the predicate function for region builders.
type Region func(*sql.Selector)

// Timezone is the predicate function for timezone builders.
type Timezone func(*sql.Selector)
