// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package regionservice

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/pb/base"

	"oa.98ent.com/p9/platform-base/rpc/pb/base/region"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegionService interface {
		// 创建国家地区
		Create(ctx context.Context, in *region.CreateRegionRequest, opts ...grpc.CallOption) (*region.CreateRegionResponse, error)
		// 修改国家地区
		Update(ctx context.Context, in *region.UpdateRegionRequest, opts ...grpc.CallOption) (*region.UpdateRegionResponse, error)
		// 获取国家地区
		Get(ctx context.Context, in *region.GetRegionRequest, opts ...grpc.CallOption) (*region.GetRegionResponse, error)
		// 获取国家地区管理列表
		List(ctx context.Context, in *region.ListRegionsRequest, opts ...grpc.CallOption) (*region.ListRegionsResponse, error)
		// 获取全部国家地区
		ListAll(ctx context.Context, in *region.ListAllRegionsRequest, opts ...grpc.CallOption) (*region.ListAllRegionsResponse, error)
		// 调整国家地区排序
		Reorder(ctx context.Context, in *region.ReorderRegionRequest, opts ...grpc.CallOption) (*region.ReorderRegionResponse, error)
	}

	defaultRegionService struct {
		cli zrpc.Client
	}
)

func NewRegionService(cli zrpc.Client) RegionService {
	return &defaultRegionService{
		cli: cli,
	}
}

// 创建国家地区
func (m *defaultRegionService) Create(ctx context.Context, in *region.CreateRegionRequest, opts ...grpc.CallOption) (*region.CreateRegionResponse, error) {
	client := base.NewRegionServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 修改国家地区
func (m *defaultRegionService) Update(ctx context.Context, in *region.UpdateRegionRequest, opts ...grpc.CallOption) (*region.UpdateRegionResponse, error) {
	client := base.NewRegionServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 获取国家地区
func (m *defaultRegionService) Get(ctx context.Context, in *region.GetRegionRequest, opts ...grpc.CallOption) (*region.GetRegionResponse, error) {
	client := base.NewRegionServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 获取国家地区管理列表
func (m *defaultRegionService) List(ctx context.Context, in *region.ListRegionsRequest, opts ...grpc.CallOption) (*region.ListRegionsResponse, error) {
	client := base.NewRegionServiceClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 获取全部国家地区
func (m *defaultRegionService) ListAll(ctx context.Context, in *region.ListAllRegionsRequest, opts ...grpc.CallOption) (*region.ListAllRegionsResponse, error) {
	client := base.NewRegionServiceClient(m.cli.Conn())
	return client.ListAll(ctx, in, opts...)
}

// 调整国家地区排序
func (m *defaultRegionService) Reorder(ctx context.Context, in *region.ReorderRegionRequest, opts ...grpc.CallOption) (*region.ReorderRegionResponse, error) {
	client := base.NewRegionServiceClient(m.cli.Conn())
	return client.Reorder(ctx, in, opts...)
}
