// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: types/language.proto

package language

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 语言信息
type LanguageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 语言编码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 多语言名称
	NameI18N map[string]string `protobuf:"bytes,3,rep,name=name_i18n,json=nameI18n,proto3" json:"name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 状态: 1启用, 2停用
	Status int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 排序值, 数值越小越靠前
	SortNo        int64 `protobuf:"varint,5,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageInfo) Reset() {
	*x = LanguageInfo{}
	mi := &file_types_language_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageInfo) ProtoMessage() {}

func (x *LanguageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageInfo.ProtoReflect.Descriptor instead.
func (*LanguageInfo) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{0}
}

func (x *LanguageInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LanguageInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LanguageInfo) GetNameI18N() map[string]string {
	if x != nil {
		return x.NameI18N
	}
	return nil
}

func (x *LanguageInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LanguageInfo) GetSortNo() int64 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

// 创建语言请求
type CreateLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言编码
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 多语言名称
	NameI18N map[string]string `protobuf:"bytes,2,rep,name=name_i18n,json=nameI18n,proto3" json:"name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLanguageRequest) Reset() {
	*x = CreateLanguageRequest{}
	mi := &file_types_language_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLanguageRequest) ProtoMessage() {}

func (x *CreateLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLanguageRequest.ProtoReflect.Descriptor instead.
func (*CreateLanguageRequest) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLanguageRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateLanguageRequest) GetNameI18N() map[string]string {
	if x != nil {
		return x.NameI18N
	}
	return nil
}

func (x *CreateLanguageRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 创建语言响应
type CreateLanguageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLanguageResponse) Reset() {
	*x = CreateLanguageResponse{}
	mi := &file_types_language_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLanguageResponse) ProtoMessage() {}

func (x *CreateLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLanguageResponse.ProtoReflect.Descriptor instead.
func (*CreateLanguageResponse) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLanguageResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改语言请求
type UpdateLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 多语言名称, 为空时不修改
	NameI18N map[string]string `protobuf:"bytes,2,rep,name=name_i18n,json=nameI18n,proto3" json:"name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLanguageRequest) Reset() {
	*x = UpdateLanguageRequest{}
	mi := &file_types_language_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLanguageRequest) ProtoMessage() {}

func (x *UpdateLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLanguageRequest.ProtoReflect.Descriptor instead.
func (*UpdateLanguageRequest) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLanguageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLanguageRequest) GetNameI18N() map[string]string {
	if x != nil {
		return x.NameI18N
	}
	return nil
}

func (x *UpdateLanguageRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 修改语言响应
type UpdateLanguageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLanguageResponse) Reset() {
	*x = UpdateLanguageResponse{}
	mi := &file_types_language_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLanguageResponse) ProtoMessage() {}

func (x *UpdateLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLanguageResponse.ProtoReflect.Descriptor instead.
func (*UpdateLanguageResponse) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{4}
}

// 获取语言请求
type GetLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguageRequest) Reset() {
	*x = GetLanguageRequest{}
	mi := &file_types_language_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageRequest) ProtoMessage() {}

func (x *GetLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageRequest.ProtoReflect.Descriptor instead.
func (*GetLanguageRequest) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{5}
}

func (x *GetLanguageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取语言响应
type GetLanguageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言信息
	Language      *LanguageInfo `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguageResponse) Reset() {
	*x = GetLanguageResponse{}
	mi := &file_types_language_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageResponse) ProtoMessage() {}

func (x *GetLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageResponse.ProtoReflect.Descriptor instead.
func (*GetLanguageResponse) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{6}
}

func (x *GetLanguageResponse) GetLanguage() *LanguageInfo {
	if x != nil {
		return x.Language
	}
	return nil
}

// 获取语言管理列表请求
type ListLanguagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码, 从1开始
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesRequest) Reset() {
	*x = ListLanguagesRequest{}
	mi := &file_types_language_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesRequest) ProtoMessage() {}

func (x *ListLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{7}
}

func (x *ListLanguagesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLanguagesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLanguagesRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取语言管理列表响应
type ListLanguagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 语言列表
	List          []*LanguageInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesResponse) Reset() {
	*x = ListLanguagesResponse{}
	mi := &file_types_language_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesResponse) ProtoMessage() {}

func (x *ListLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{8}
}

func (x *ListLanguagesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLanguagesResponse) GetList() []*LanguageInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取全部语言请求
type ListAllLanguagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllLanguagesRequest) Reset() {
	*x = ListAllLanguagesRequest{}
	mi := &file_types_language_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllLanguagesRequest) ProtoMessage() {}

func (x *ListAllLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListAllLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllLanguagesRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取全部语言响应
type ListAllLanguagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言列表
	List          []*LanguageInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllLanguagesResponse) Reset() {
	*x = ListAllLanguagesResponse{}
	mi := &file_types_language_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllLanguagesResponse) ProtoMessage() {}

func (x *ListAllLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListAllLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{10}
}

func (x *ListAllLanguagesResponse) GetList() []*LanguageInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 调整语言排序请求
type ReorderLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 需要移动的语言ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 目标语言ID
	TargetId      int64 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderLanguageRequest) Reset() {
	*x = ReorderLanguageRequest{}
	mi := &file_types_language_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderLanguageRequest) ProtoMessage() {}

func (x *ReorderLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderLanguageRequest.ProtoReflect.Descriptor instead.
func (*ReorderLanguageRequest) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{11}
}

func (x *ReorderLanguageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReorderLanguageRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 调整语言排序响应
type ReorderLanguageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderLanguageResponse) Reset() {
	*x = ReorderLanguageResponse{}
	mi := &file_types_language_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderLanguageResponse) ProtoMessage() {}

func (x *ReorderLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderLanguageResponse.ProtoReflect.Descriptor instead.
func (*ReorderLanguageResponse) Descriptor() ([]byte, []int) {
	return file_types_language_proto_rawDescGZIP(), []int{12}
}

var File_types_language_proto protoreflect.FileDescriptor

const file_types_language_proto_rawDesc = "" +
	"\n" +
	"\x14types/language.proto\x12\blanguage\"\xe3\x01\n" +
	"\fLanguageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12A\n" +
	"\tname_i18n\x18\x03 \x03(\v2$.language.LanguageInfo.NameI18nEntryR\bnameI18n\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x17\n" +
	"\asort_no\x18\x05 \x01(\x03R\x06sortNo\x1a;\n" +
	"\rNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x15CreateLanguageRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12J\n" +
	"\tname_i18n\x18\x02 \x03(\v2-.language.CreateLanguageRequest.NameI18nEntryR\bnameI18n\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x03H\x00R\x06status\x88\x01\x01\x1a;\n" +
	"\rNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_status\"(\n" +
	"\x16CreateLanguageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd8\x01\n" +
	"\x15UpdateLanguageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12J\n" +
	"\tname_i18n\x18\x02 \x03(\v2-.language.UpdateLanguageRequest.NameI18nEntryR\bnameI18n\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x03H\x00R\x06status\x88\x01\x01\x1a;\n" +
	"\rNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_status\"\x18\n" +
	"\x16UpdateLanguageResponse\"$\n" +
	"\x12GetLanguageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x13GetLanguageResponse\x122\n" +
	"\blanguage\x18\x01 \x01(\v2\x16.language.LanguageInfoR\blanguage\"o\n" +
	"\x14ListLanguagesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x03H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"Y\n" +
	"\x15ListLanguagesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.language.LanguageInfoR\x04list\"A\n" +
	"\x17ListAllLanguagesRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x03H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"F\n" +
	"\x18ListAllLanguagesResponse\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.language.LanguageInfoR\x04list\"E\n" +
	"\x16ReorderLanguageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\"\x19\n" +
	"\x17ReorderLanguageResponseB4Z2oa.98ent.com/p9/platform-base/rpc/pb/base/languageb\x06proto3"

var (
	file_types_language_proto_rawDescOnce sync.Once
	file_types_language_proto_rawDescData []byte
)

func file_types_language_proto_rawDescGZIP() []byte {
	file_types_language_proto_rawDescOnce.Do(func() {
		file_types_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_language_proto_rawDesc), len(file_types_language_proto_rawDesc)))
	})
	return file_types_language_proto_rawDescData
}

var file_types_language_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_types_language_proto_goTypes = []any{
	(*LanguageInfo)(nil),             // 0: language.LanguageInfo
	(*CreateLanguageRequest)(nil),    // 1: language.CreateLanguageRequest
	(*CreateLanguageResponse)(nil),   // 2: language.CreateLanguageResponse
	(*UpdateLanguageRequest)(nil),    // 3: language.UpdateLanguageRequest
	(*UpdateLanguageResponse)(nil),   // 4: language.UpdateLanguageResponse
	(*GetLanguageRequest)(nil),       // 5: language.GetLanguageRequest
	(*GetLanguageResponse)(nil),      // 6: language.GetLanguageResponse
	(*ListLanguagesRequest)(nil),     // 7: language.ListLanguagesRequest
	(*ListLanguagesResponse)(nil),    // 8: language.ListLanguagesResponse
	(*ListAllLanguagesRequest)(nil),  // 9: language.ListAllLanguagesRequest
	(*ListAllLanguagesResponse)(nil), // 10: language.ListAllLanguagesResponse
	(*ReorderLanguageRequest)(nil),   // 11: language.ReorderLanguageRequest
	(*ReorderLanguageResponse)(nil),  // 12: language.ReorderLanguageResponse
	nil,                              // 13: language.LanguageInfo.NameI18nEntry
	nil,                              // 14: language.CreateLanguageRequest.NameI18nEntry
	nil,                              // 15: language.UpdateLanguageRequest.NameI18nEntry
}
var file_types_language_proto_depIdxs = []int32{
	13, // 0: language.LanguageInfo.name_i18n:type_name -> language.LanguageInfo.NameI18nEntry
	14, // 1: language.CreateLanguageRequest.name_i18n:type_name -> language.CreateLanguageRequest.NameI18nEntry
	15, // 2: language.UpdateLanguageRequest.name_i18n:type_name -> language.UpdateLanguageRequest.NameI18nEntry
	0,  // 3: language.GetLanguageResponse.language:type_name -> language.LanguageInfo
	0,  // 4: language.ListLanguagesResponse.list:type_name -> language.LanguageInfo
	0,  // 5: language.ListAllLanguagesResponse.list:type_name -> language.LanguageInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_types_language_proto_init() }
func file_types_language_proto_init() {
	if File_types_language_proto != nil {
		return
	}
	file_types_language_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_language_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_language_proto_msgTypes[7].OneofWrappers = []any{}
	file_types_language_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_language_proto_rawDesc), len(file_types_language_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_language_proto_goTypes,
		DependencyIndexes: file_types_language_proto_depIdxs,
		MessageInfos:      file_types_language_proto_msgTypes,
	}.Build()
	File_types_language_proto = out.File
	file_types_language_proto_goTypes = nil
	file_types_language_proto_depIdxs = nil
}
