// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package currencyservice

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/pb/base"

	"oa.98ent.com/p9/platform-base/rpc/pb/base/currency"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CurrencyService interface {
		// 创建货币
		Create(ctx context.Context, in *currency.CreateCurrencyRequest, opts ...grpc.CallOption) (*currency.CreateCurrencyResponse, error)
		// 修改货币
		Update(ctx context.Context, in *currency.UpdateCurrencyRequest, opts ...grpc.CallOption) (*currency.UpdateCurrencyResponse, error)
		// 获取货币
		Get(ctx context.Context, in *currency.GetCurrencyRequest, opts ...grpc.CallOption) (*currency.GetCurrencyResponse, error)
		// 获取货币管理列表
		List(ctx context.Context, in *currency.ListCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListCurrenciesResponse, error)
		// 获取全部货币
		ListAll(ctx context.Context, in *currency.ListAllCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListAllCurrenciesResponse, error)
		// 调整货币排序
		Reorder(ctx context.Context, in *currency.ReorderCurrencyRequest, opts ...grpc.CallOption) (*currency.ReorderCurrencyResponse, error)
	}

	defaultCurrencyService struct {
		cli zrpc.Client
	}
)

func NewCurrencyService(cli zrpc.Client) CurrencyService {
	return &defaultCurrencyService{
		cli: cli,
	}
}

// 创建货币
func (m *defaultCurrencyService) Create(ctx context.Context, in *currency.CreateCurrencyRequest, opts ...grpc.CallOption) (*currency.CreateCurrencyResponse, error) {
	client := base.NewCurrencyServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 修改货币
func (m *defaultCurrencyService) Update(ctx context.Context, in *currency.UpdateCurrencyRequest, opts ...grpc.CallOption) (*currency.UpdateCurrencyResponse, error) {
	client := base.NewCurrencyServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 获取货币
func (m *defaultCurrencyService) Get(ctx context.Context, in *currency.GetCurrencyRequest, opts ...grpc.CallOption) (*currency.GetCurrencyResponse, error) {
	client := base.NewCurrencyServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 获取货币管理列表
func (m *defaultCurrencyService) List(ctx context.Context, in *currency.ListCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListCurrenciesResponse, error) {
	client := base.NewCurrencyServiceClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 获取全部货币
func (m *defaultCurrencyService) ListAll(ctx context.Context, in *currency.ListAllCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListAllCurrenciesResponse, error) {
	client := base.NewCurrencyServiceClient(m.cli.Conn())
	return client.ListAll(ctx, in, opts...)
}

// 调整货币排序
func (m *defaultCurrencyService) Reorder(ctx context.Context, in *currency.ReorderCurrencyRequest, opts ...grpc.CallOption) (*currency.ReorderCurrencyResponse, error) {
	client := base.NewCurrencyServiceClient(m.cli.Conn())
	return client.Reorder(ctx, in, opts...)
}
