// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package pingservice

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/pb/base"

	"oa.98ent.com/p9/platform-base/rpc/pb/base/ping"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingService interface {
		// Ping
		Ping(ctx context.Context, in *ping.PingRequest, opts ...grpc.CallOption) (*ping.PingResponse, error)
	}

	defaultPingService struct {
		cli zrpc.Client
	}
)

func NewPingService(cli zrpc.Client) PingService {
	return &defaultPingService{
		cli: cli,
	}
}

// Ping
func (m *defaultPingService) Ping(ctx context.Context, in *ping.PingRequest, opts ...grpc.CallOption) (*ping.PingResponse, error) {
	client := base.NewPingServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
