// Code generated by ent, DO NOT EDIT.

package region

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/platform-base/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldStatus, v))
}

// SortNo applies equality check predicate on the "sort_no" field. It's identical to SortNoEQ.
func SortNo(v int64) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldSortNo, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldUpdatedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldCode, v))
}

// CallingCode applies equality check predicate on the "calling_code" field. It's identical to CallingCodeEQ.
func CallingCode(v string) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldCallingCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldStatus, v))
}

// SortNoEQ applies the EQ predicate on the "sort_no" field.
func SortNoEQ(v int64) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldSortNo, v))
}

// SortNoNEQ applies the NEQ predicate on the "sort_no" field.
func SortNoNEQ(v int64) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldSortNo, v))
}

// SortNoIn applies the In predicate on the "sort_no" field.
func SortNoIn(vs ...int64) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldSortNo, vs...))
}

// SortNoNotIn applies the NotIn predicate on the "sort_no" field.
func SortNoNotIn(vs ...int64) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldSortNo, vs...))
}

// SortNoGT applies the GT predicate on the "sort_no" field.
func SortNoGT(v int64) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldSortNo, v))
}

// SortNoGTE applies the GTE predicate on the "sort_no" field.
func SortNoGTE(v int64) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldSortNo, v))
}

// SortNoLT applies the LT predicate on the "sort_no" field.
func SortNoLT(v int64) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldSortNo, v))
}

// SortNoLTE applies the LTE predicate on the "sort_no" field.
func SortNoLTE(v int64) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldSortNo, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Region {
	return predicate.Region(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Region {
	return predicate.Region(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Region {
	return predicate.Region(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Region {
	return predicate.Region(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Region {
	return predicate.Region(sql.FieldContainsFold(FieldCode, v))
}

// CallingCodeEQ applies the EQ predicate on the "calling_code" field.
func CallingCodeEQ(v string) predicate.Region {
	return predicate.Region(sql.FieldEQ(FieldCallingCode, v))
}

// CallingCodeNEQ applies the NEQ predicate on the "calling_code" field.
func CallingCodeNEQ(v string) predicate.Region {
	return predicate.Region(sql.FieldNEQ(FieldCallingCode, v))
}

// CallingCodeIn applies the In predicate on the "calling_code" field.
func CallingCodeIn(vs ...string) predicate.Region {
	return predicate.Region(sql.FieldIn(FieldCallingCode, vs...))
}

// CallingCodeNotIn applies the NotIn predicate on the "calling_code" field.
func CallingCodeNotIn(vs ...string) predicate.Region {
	return predicate.Region(sql.FieldNotIn(FieldCallingCode, vs...))
}

// CallingCodeGT applies the GT predicate on the "calling_code" field.
func CallingCodeGT(v string) predicate.Region {
	return predicate.Region(sql.FieldGT(FieldCallingCode, v))
}

// CallingCodeGTE applies the GTE predicate on the "calling_code" field.
func CallingCodeGTE(v string) predicate.Region {
	return predicate.Region(sql.FieldGTE(FieldCallingCode, v))
}

// CallingCodeLT applies the LT predicate on the "calling_code" field.
func CallingCodeLT(v string) predicate.Region {
	return predicate.Region(sql.FieldLT(FieldCallingCode, v))
}

// CallingCodeLTE applies the LTE predicate on the "calling_code" field.
func CallingCodeLTE(v string) predicate.Region {
	return predicate.Region(sql.FieldLTE(FieldCallingCode, v))
}

// CallingCodeContains applies the Contains predicate on the "calling_code" field.
func CallingCodeContains(v string) predicate.Region {
	return predicate.Region(sql.FieldContains(FieldCallingCode, v))
}

// CallingCodeHasPrefix applies the HasPrefix predicate on the "calling_code" field.
func CallingCodeHasPrefix(v string) predicate.Region {
	return predicate.Region(sql.FieldHasPrefix(FieldCallingCode, v))
}

// CallingCodeHasSuffix applies the HasSuffix predicate on the "calling_code" field.
func CallingCodeHasSuffix(v string) predicate.Region {
	return predicate.Region(sql.FieldHasSuffix(FieldCallingCode, v))
}

// CallingCodeEqualFold applies the EqualFold predicate on the "calling_code" field.
func CallingCodeEqualFold(v string) predicate.Region {
	return predicate.Region(sql.FieldEqualFold(FieldCallingCode, v))
}

// CallingCodeContainsFold applies the ContainsFold predicate on the "calling_code" field.
func CallingCodeContainsFold(v string) predicate.Region {
	return predicate.Region(sql.FieldContainsFold(FieldCallingCode, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Region) predicate.Region {
	return predicate.Region(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Region) predicate.Region {
	return predicate.Region(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Region) predicate.Region {
	return predicate.Region(sql.NotPredicates(p))
}
