// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/internal/logic/timezoneservice"
	"oa.98ent.com/p9/platform-base/rpc/internal/svc"
	"oa.98ent.com/p9/platform-base/rpc/pb/base"
	"oa.98ent.com/p9/platform-base/rpc/pb/base/timezone"
)

type TimezoneServiceServer struct {
	svcCtx *svc.ServiceContext
	base.UnimplementedTimezoneServiceServer
}

func NewTimezoneServiceServer(svcCtx *svc.ServiceContext) *TimezoneServiceServer {
	return &TimezoneServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建时区
func (s *TimezoneServiceServer) Create(ctx context.Context, in *timezone.CreateTimezoneRequest) (*timezone.CreateTimezoneResponse, error) {
	l := timezoneservicelogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

// 修改时区
func (s *TimezoneServiceServer) Update(ctx context.Context, in *timezone.UpdateTimezoneRequest) (*timezone.UpdateTimezoneResponse, error) {
	l := timezoneservicelogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

// 获取时区
func (s *TimezoneServiceServer) Get(ctx context.Context, in *timezone.GetTimezoneRequest) (*timezone.GetTimezoneResponse, error) {
	l := timezoneservicelogic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

// 获取时区管理列表
func (s *TimezoneServiceServer) List(ctx context.Context, in *timezone.ListTimezonesRequest) (*timezone.ListTimezonesResponse, error) {
	l := timezoneservicelogic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 获取全部时区
func (s *TimezoneServiceServer) ListAll(ctx context.Context, in *timezone.ListAllTimezonesRequest) (*timezone.ListAllTimezonesResponse, error) {
	l := timezoneservicelogic.NewListAllLogic(ctx, s.svcCtx)
	return l.ListAll(in)
}

// 调整时区排序
func (s *TimezoneServiceServer) Reorder(ctx context.Context, in *timezone.ReorderTimezoneRequest) (*timezone.ReorderTimezoneResponse, error) {
	l := timezoneservicelogic.NewReorderLogic(ctx, s.svcCtx)
	return l.Reorder(in)
}
