// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: platform_base.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	currency "oa.98ent.com/p9/platform-base/rpc/pb/base/currency"
	language "oa.98ent.com/p9/platform-base/rpc/pb/base/language"
	ping "oa.98ent.com/p9/platform-base/rpc/pb/base/ping"
	region "oa.98ent.com/p9/platform-base/rpc/pb/base/region"
	timezone "oa.98ent.com/p9/platform-base/rpc/pb/base/timezone"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingService_Ping_FullMethodName = "/platform_base.PingService/Ping"
)

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ping 服务
type PingServiceClient interface {
	// Ping
	Ping(ctx context.Context, in *ping.PingRequest, opts ...grpc.CallOption) (*ping.PingResponse, error)
}

type pingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingServiceClient(cc grpc.ClientConnInterface) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Ping(ctx context.Context, in *ping.PingRequest, opts ...grpc.CallOption) (*ping.PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ping.PingResponse)
	err := c.cc.Invoke(ctx, PingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServiceServer is the server API for PingService service.
// All implementations must embed UnimplementedPingServiceServer
// for forward compatibility.
//
// Ping 服务
type PingServiceServer interface {
	// Ping
	Ping(context.Context, *ping.PingRequest) (*ping.PingResponse, error)
	mustEmbedUnimplementedPingServiceServer()
}

// UnimplementedPingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingServiceServer struct{}

func (UnimplementedPingServiceServer) Ping(context.Context, *ping.PingRequest) (*ping.PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPingServiceServer) mustEmbedUnimplementedPingServiceServer() {}
func (UnimplementedPingServiceServer) testEmbeddedByValue()                     {}

// UnsafePingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingServiceServer will
// result in compilation errors.
type UnsafePingServiceServer interface {
	mustEmbedUnimplementedPingServiceServer()
}

func RegisterPingServiceServer(s grpc.ServiceRegistrar, srv PingServiceServer) {
	// If the following call panics, it indicates UnimplementedPingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingService_ServiceDesc, srv)
}

func _PingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ping.PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Ping(ctx, req.(*ping.PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PingService_ServiceDesc is the grpc.ServiceDesc for PingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_base.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_base.proto",
}

const (
	LanguageService_Create_FullMethodName  = "/platform_base.LanguageService/Create"
	LanguageService_Update_FullMethodName  = "/platform_base.LanguageService/Update"
	LanguageService_Get_FullMethodName     = "/platform_base.LanguageService/Get"
	LanguageService_List_FullMethodName    = "/platform_base.LanguageService/List"
	LanguageService_ListAll_FullMethodName = "/platform_base.LanguageService/ListAll"
	LanguageService_Reorder_FullMethodName = "/platform_base.LanguageService/Reorder"
)

// LanguageServiceClient is the client API for LanguageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 语言服务
type LanguageServiceClient interface {
	// 创建语言
	Create(ctx context.Context, in *language.CreateLanguageRequest, opts ...grpc.CallOption) (*language.CreateLanguageResponse, error)
	// 修改语言
	Update(ctx context.Context, in *language.UpdateLanguageRequest, opts ...grpc.CallOption) (*language.UpdateLanguageResponse, error)
	// 获取语言
	Get(ctx context.Context, in *language.GetLanguageRequest, opts ...grpc.CallOption) (*language.GetLanguageResponse, error)
	// 获取语言管理列表
	List(ctx context.Context, in *language.ListLanguagesRequest, opts ...grpc.CallOption) (*language.ListLanguagesResponse, error)
	// 获取全部语言
	ListAll(ctx context.Context, in *language.ListAllLanguagesRequest, opts ...grpc.CallOption) (*language.ListAllLanguagesResponse, error)
	// 调整语言排序
	Reorder(ctx context.Context, in *language.ReorderLanguageRequest, opts ...grpc.CallOption) (*language.ReorderLanguageResponse, error)
}

type languageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanguageServiceClient(cc grpc.ClientConnInterface) LanguageServiceClient {
	return &languageServiceClient{cc}
}

func (c *languageServiceClient) Create(ctx context.Context, in *language.CreateLanguageRequest, opts ...grpc.CallOption) (*language.CreateLanguageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(language.CreateLanguageResponse)
	err := c.cc.Invoke(ctx, LanguageService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageServiceClient) Update(ctx context.Context, in *language.UpdateLanguageRequest, opts ...grpc.CallOption) (*language.UpdateLanguageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(language.UpdateLanguageResponse)
	err := c.cc.Invoke(ctx, LanguageService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageServiceClient) Get(ctx context.Context, in *language.GetLanguageRequest, opts ...grpc.CallOption) (*language.GetLanguageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(language.GetLanguageResponse)
	err := c.cc.Invoke(ctx, LanguageService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageServiceClient) List(ctx context.Context, in *language.ListLanguagesRequest, opts ...grpc.CallOption) (*language.ListLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(language.ListLanguagesResponse)
	err := c.cc.Invoke(ctx, LanguageService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageServiceClient) ListAll(ctx context.Context, in *language.ListAllLanguagesRequest, opts ...grpc.CallOption) (*language.ListAllLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(language.ListAllLanguagesResponse)
	err := c.cc.Invoke(ctx, LanguageService_ListAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageServiceClient) Reorder(ctx context.Context, in *language.ReorderLanguageRequest, opts ...grpc.CallOption) (*language.ReorderLanguageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(language.ReorderLanguageResponse)
	err := c.cc.Invoke(ctx, LanguageService_Reorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanguageServiceServer is the server API for LanguageService service.
// All implementations must embed UnimplementedLanguageServiceServer
// for forward compatibility.
//
// 语言服务
type LanguageServiceServer interface {
	// 创建语言
	Create(context.Context, *language.CreateLanguageRequest) (*language.CreateLanguageResponse, error)
	// 修改语言
	Update(context.Context, *language.UpdateLanguageRequest) (*language.UpdateLanguageResponse, error)
	// 获取语言
	Get(context.Context, *language.GetLanguageRequest) (*language.GetLanguageResponse, error)
	// 获取语言管理列表
	List(context.Context, *language.ListLanguagesRequest) (*language.ListLanguagesResponse, error)
	// 获取全部语言
	ListAll(context.Context, *language.ListAllLanguagesRequest) (*language.ListAllLanguagesResponse, error)
	// 调整语言排序
	Reorder(context.Context, *language.ReorderLanguageRequest) (*language.ReorderLanguageResponse, error)
	mustEmbedUnimplementedLanguageServiceServer()
}

// UnimplementedLanguageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanguageServiceServer struct{}

func (UnimplementedLanguageServiceServer) Create(context.Context, *language.CreateLanguageRequest) (*language.CreateLanguageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLanguageServiceServer) Update(context.Context, *language.UpdateLanguageRequest) (*language.UpdateLanguageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedLanguageServiceServer) Get(context.Context, *language.GetLanguageRequest) (*language.GetLanguageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLanguageServiceServer) List(context.Context, *language.ListLanguagesRequest) (*language.ListLanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLanguageServiceServer) ListAll(context.Context, *language.ListAllLanguagesRequest) (*language.ListAllLanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedLanguageServiceServer) Reorder(context.Context, *language.ReorderLanguageRequest) (*language.ReorderLanguageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reorder not implemented")
}
func (UnimplementedLanguageServiceServer) mustEmbedUnimplementedLanguageServiceServer() {}
func (UnimplementedLanguageServiceServer) testEmbeddedByValue()                         {}

// UnsafeLanguageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanguageServiceServer will
// result in compilation errors.
type UnsafeLanguageServiceServer interface {
	mustEmbedUnimplementedLanguageServiceServer()
}

func RegisterLanguageServiceServer(s grpc.ServiceRegistrar, srv LanguageServiceServer) {
	// If the following call panics, it indicates UnimplementedLanguageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanguageService_ServiceDesc, srv)
}

func _LanguageService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(language.CreateLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServiceServer).Create(ctx, req.(*language.CreateLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(language.UpdateLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServiceServer).Update(ctx, req.(*language.UpdateLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(language.GetLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServiceServer).Get(ctx, req.(*language.GetLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(language.ListLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServiceServer).List(ctx, req.(*language.ListLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(language.ListAllLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageService_ListAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServiceServer).ListAll(ctx, req.(*language.ListAllLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageService_Reorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(language.ReorderLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServiceServer).Reorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageService_Reorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServiceServer).Reorder(ctx, req.(*language.ReorderLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanguageService_ServiceDesc is the grpc.ServiceDesc for LanguageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanguageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_base.LanguageService",
	HandlerType: (*LanguageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LanguageService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _LanguageService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LanguageService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _LanguageService_List_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _LanguageService_ListAll_Handler,
		},
		{
			MethodName: "Reorder",
			Handler:    _LanguageService_Reorder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_base.proto",
}

const (
	TimezoneService_Create_FullMethodName  = "/platform_base.TimezoneService/Create"
	TimezoneService_Update_FullMethodName  = "/platform_base.TimezoneService/Update"
	TimezoneService_Get_FullMethodName     = "/platform_base.TimezoneService/Get"
	TimezoneService_List_FullMethodName    = "/platform_base.TimezoneService/List"
	TimezoneService_ListAll_FullMethodName = "/platform_base.TimezoneService/ListAll"
	TimezoneService_Reorder_FullMethodName = "/platform_base.TimezoneService/Reorder"
)

// TimezoneServiceClient is the client API for TimezoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 时区服务
type TimezoneServiceClient interface {
	// 创建时区
	Create(ctx context.Context, in *timezone.CreateTimezoneRequest, opts ...grpc.CallOption) (*timezone.CreateTimezoneResponse, error)
	// 修改时区
	Update(ctx context.Context, in *timezone.UpdateTimezoneRequest, opts ...grpc.CallOption) (*timezone.UpdateTimezoneResponse, error)
	// 获取时区
	Get(ctx context.Context, in *timezone.GetTimezoneRequest, opts ...grpc.CallOption) (*timezone.GetTimezoneResponse, error)
	// 获取时区管理列表
	List(ctx context.Context, in *timezone.ListTimezonesRequest, opts ...grpc.CallOption) (*timezone.ListTimezonesResponse, error)
	// 获取全部时区
	ListAll(ctx context.Context, in *timezone.ListAllTimezonesRequest, opts ...grpc.CallOption) (*timezone.ListAllTimezonesResponse, error)
	// 调整时区排序
	Reorder(ctx context.Context, in *timezone.ReorderTimezoneRequest, opts ...grpc.CallOption) (*timezone.ReorderTimezoneResponse, error)
}

type timezoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimezoneServiceClient(cc grpc.ClientConnInterface) TimezoneServiceClient {
	return &timezoneServiceClient{cc}
}

func (c *timezoneServiceClient) Create(ctx context.Context, in *timezone.CreateTimezoneRequest, opts ...grpc.CallOption) (*timezone.CreateTimezoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(timezone.CreateTimezoneResponse)
	err := c.cc.Invoke(ctx, TimezoneService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timezoneServiceClient) Update(ctx context.Context, in *timezone.UpdateTimezoneRequest, opts ...grpc.CallOption) (*timezone.UpdateTimezoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(timezone.UpdateTimezoneResponse)
	err := c.cc.Invoke(ctx, TimezoneService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timezoneServiceClient) Get(ctx context.Context, in *timezone.GetTimezoneRequest, opts ...grpc.CallOption) (*timezone.GetTimezoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(timezone.GetTimezoneResponse)
	err := c.cc.Invoke(ctx, TimezoneService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timezoneServiceClient) List(ctx context.Context, in *timezone.ListTimezonesRequest, opts ...grpc.CallOption) (*timezone.ListTimezonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(timezone.ListTimezonesResponse)
	err := c.cc.Invoke(ctx, TimezoneService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timezoneServiceClient) ListAll(ctx context.Context, in *timezone.ListAllTimezonesRequest, opts ...grpc.CallOption) (*timezone.ListAllTimezonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(timezone.ListAllTimezonesResponse)
	err := c.cc.Invoke(ctx, TimezoneService_ListAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timezoneServiceClient) Reorder(ctx context.Context, in *timezone.ReorderTimezoneRequest, opts ...grpc.CallOption) (*timezone.ReorderTimezoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(timezone.ReorderTimezoneResponse)
	err := c.cc.Invoke(ctx, TimezoneService_Reorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimezoneServiceServer is the server API for TimezoneService service.
// All implementations must embed UnimplementedTimezoneServiceServer
// for forward compatibility.
//
// 时区服务
type TimezoneServiceServer interface {
	// 创建时区
	Create(context.Context, *timezone.CreateTimezoneRequest) (*timezone.CreateTimezoneResponse, error)
	// 修改时区
	Update(context.Context, *timezone.UpdateTimezoneRequest) (*timezone.UpdateTimezoneResponse, error)
	// 获取时区
	Get(context.Context, *timezone.GetTimezoneRequest) (*timezone.GetTimezoneResponse, error)
	// 获取时区管理列表
	List(context.Context, *timezone.ListTimezonesRequest) (*timezone.ListTimezonesResponse, error)
	// 获取全部时区
	ListAll(context.Context, *timezone.ListAllTimezonesRequest) (*timezone.ListAllTimezonesResponse, error)
	// 调整时区排序
	Reorder(context.Context, *timezone.ReorderTimezoneRequest) (*timezone.ReorderTimezoneResponse, error)
	mustEmbedUnimplementedTimezoneServiceServer()
}

// UnimplementedTimezoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimezoneServiceServer struct{}

func (UnimplementedTimezoneServiceServer) Create(context.Context, *timezone.CreateTimezoneRequest) (*timezone.CreateTimezoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTimezoneServiceServer) Update(context.Context, *timezone.UpdateTimezoneRequest) (*timezone.UpdateTimezoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTimezoneServiceServer) Get(context.Context, *timezone.GetTimezoneRequest) (*timezone.GetTimezoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTimezoneServiceServer) List(context.Context, *timezone.ListTimezonesRequest) (*timezone.ListTimezonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTimezoneServiceServer) ListAll(context.Context, *timezone.ListAllTimezonesRequest) (*timezone.ListAllTimezonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedTimezoneServiceServer) Reorder(context.Context, *timezone.ReorderTimezoneRequest) (*timezone.ReorderTimezoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reorder not implemented")
}
func (UnimplementedTimezoneServiceServer) mustEmbedUnimplementedTimezoneServiceServer() {}
func (UnimplementedTimezoneServiceServer) testEmbeddedByValue()                         {}

// UnsafeTimezoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimezoneServiceServer will
// result in compilation errors.
type UnsafeTimezoneServiceServer interface {
	mustEmbedUnimplementedTimezoneServiceServer()
}

func RegisterTimezoneServiceServer(s grpc.ServiceRegistrar, srv TimezoneServiceServer) {
	// If the following call panics, it indicates UnimplementedTimezoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimezoneService_ServiceDesc, srv)
}

func _TimezoneService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timezone.CreateTimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimezoneService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).Create(ctx, req.(*timezone.CreateTimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimezoneService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timezone.UpdateTimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimezoneService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).Update(ctx, req.(*timezone.UpdateTimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimezoneService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timezone.GetTimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimezoneService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).Get(ctx, req.(*timezone.GetTimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimezoneService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timezone.ListTimezonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimezoneService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).List(ctx, req.(*timezone.ListTimezonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimezoneService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timezone.ListAllTimezonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimezoneService_ListAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).ListAll(ctx, req.(*timezone.ListAllTimezonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimezoneService_Reorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timezone.ReorderTimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).Reorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimezoneService_Reorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).Reorder(ctx, req.(*timezone.ReorderTimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimezoneService_ServiceDesc is the grpc.ServiceDesc for TimezoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimezoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_base.TimezoneService",
	HandlerType: (*TimezoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TimezoneService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TimezoneService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TimezoneService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TimezoneService_List_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _TimezoneService_ListAll_Handler,
		},
		{
			MethodName: "Reorder",
			Handler:    _TimezoneService_Reorder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_base.proto",
}

const (
	CurrencyService_Create_FullMethodName  = "/platform_base.CurrencyService/Create"
	CurrencyService_Update_FullMethodName  = "/platform_base.CurrencyService/Update"
	CurrencyService_Get_FullMethodName     = "/platform_base.CurrencyService/Get"
	CurrencyService_List_FullMethodName    = "/platform_base.CurrencyService/List"
	CurrencyService_ListAll_FullMethodName = "/platform_base.CurrencyService/ListAll"
	CurrencyService_Reorder_FullMethodName = "/platform_base.CurrencyService/Reorder"
)

// CurrencyServiceClient is the client API for CurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 货币服务
type CurrencyServiceClient interface {
	// 创建货币
	Create(ctx context.Context, in *currency.CreateCurrencyRequest, opts ...grpc.CallOption) (*currency.CreateCurrencyResponse, error)
	// 修改货币
	Update(ctx context.Context, in *currency.UpdateCurrencyRequest, opts ...grpc.CallOption) (*currency.UpdateCurrencyResponse, error)
	// 获取货币
	Get(ctx context.Context, in *currency.GetCurrencyRequest, opts ...grpc.CallOption) (*currency.GetCurrencyResponse, error)
	// 获取货币管理列表
	List(ctx context.Context, in *currency.ListCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListCurrenciesResponse, error)
	// 获取全部货币
	ListAll(ctx context.Context, in *currency.ListAllCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListAllCurrenciesResponse, error)
	// 调整货币排序
	Reorder(ctx context.Context, in *currency.ReorderCurrencyRequest, opts ...grpc.CallOption) (*currency.ReorderCurrencyResponse, error)
}

type currencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyServiceClient(cc grpc.ClientConnInterface) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) Create(ctx context.Context, in *currency.CreateCurrencyRequest, opts ...grpc.CallOption) (*currency.CreateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(currency.CreateCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) Update(ctx context.Context, in *currency.UpdateCurrencyRequest, opts ...grpc.CallOption) (*currency.UpdateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(currency.UpdateCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) Get(ctx context.Context, in *currency.GetCurrencyRequest, opts ...grpc.CallOption) (*currency.GetCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(currency.GetCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) List(ctx context.Context, in *currency.ListCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(currency.ListCurrenciesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) ListAll(ctx context.Context, in *currency.ListAllCurrenciesRequest, opts ...grpc.CallOption) (*currency.ListAllCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(currency.ListAllCurrenciesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_ListAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) Reorder(ctx context.Context, in *currency.ReorderCurrencyRequest, opts ...grpc.CallOption) (*currency.ReorderCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(currency.ReorderCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_Reorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyServiceServer is the server API for CurrencyService service.
// All implementations must embed UnimplementedCurrencyServiceServer
// for forward compatibility.
//
// 货币服务
type CurrencyServiceServer interface {
	// 创建货币
	Create(context.Context, *currency.CreateCurrencyRequest) (*currency.CreateCurrencyResponse, error)
	// 修改货币
	Update(context.Context, *currency.UpdateCurrencyRequest) (*currency.UpdateCurrencyResponse, error)
	// 获取货币
	Get(context.Context, *currency.GetCurrencyRequest) (*currency.GetCurrencyResponse, error)
	// 获取货币管理列表
	List(context.Context, *currency.ListCurrenciesRequest) (*currency.ListCurrenciesResponse, error)
	// 获取全部货币
	ListAll(context.Context, *currency.ListAllCurrenciesRequest) (*currency.ListAllCurrenciesResponse, error)
	// 调整货币排序
	Reorder(context.Context, *currency.ReorderCurrencyRequest) (*currency.ReorderCurrencyResponse, error)
	mustEmbedUnimplementedCurrencyServiceServer()
}

// UnimplementedCurrencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyServiceServer struct{}

func (UnimplementedCurrencyServiceServer) Create(context.Context, *currency.CreateCurrencyRequest) (*currency.CreateCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCurrencyServiceServer) Update(context.Context, *currency.UpdateCurrencyRequest) (*currency.UpdateCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCurrencyServiceServer) Get(context.Context, *currency.GetCurrencyRequest) (*currency.GetCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCurrencyServiceServer) List(context.Context, *currency.ListCurrenciesRequest) (*currency.ListCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCurrencyServiceServer) ListAll(context.Context, *currency.ListAllCurrenciesRequest) (*currency.ListAllCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedCurrencyServiceServer) Reorder(context.Context, *currency.ReorderCurrencyRequest) (*currency.ReorderCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reorder not implemented")
}
func (UnimplementedCurrencyServiceServer) mustEmbedUnimplementedCurrencyServiceServer() {}
func (UnimplementedCurrencyServiceServer) testEmbeddedByValue()                         {}

// UnsafeCurrencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServiceServer will
// result in compilation errors.
type UnsafeCurrencyServiceServer interface {
	mustEmbedUnimplementedCurrencyServiceServer()
}

func RegisterCurrencyServiceServer(s grpc.ServiceRegistrar, srv CurrencyServiceServer) {
	// If the following call panics, it indicates UnimplementedCurrencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyService_ServiceDesc, srv)
}

func _CurrencyService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(currency.CreateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).Create(ctx, req.(*currency.CreateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(currency.UpdateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).Update(ctx, req.(*currency.UpdateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(currency.GetCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).Get(ctx, req.(*currency.GetCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(currency.ListCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).List(ctx, req.(*currency.ListCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(currency.ListAllCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_ListAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).ListAll(ctx, req.(*currency.ListAllCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_Reorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(currency.ReorderCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).Reorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_Reorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).Reorder(ctx, req.(*currency.ReorderCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyService_ServiceDesc is the grpc.ServiceDesc for CurrencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_base.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CurrencyService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CurrencyService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CurrencyService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CurrencyService_List_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _CurrencyService_ListAll_Handler,
		},
		{
			MethodName: "Reorder",
			Handler:    _CurrencyService_Reorder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_base.proto",
}

const (
	RegionService_Create_FullMethodName  = "/platform_base.RegionService/Create"
	RegionService_Update_FullMethodName  = "/platform_base.RegionService/Update"
	RegionService_Get_FullMethodName     = "/platform_base.RegionService/Get"
	RegionService_List_FullMethodName    = "/platform_base.RegionService/List"
	RegionService_ListAll_FullMethodName = "/platform_base.RegionService/ListAll"
	RegionService_Reorder_FullMethodName = "/platform_base.RegionService/Reorder"
)

// RegionServiceClient is the client API for RegionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 国家地区服务
type RegionServiceClient interface {
	// 创建国家地区
	Create(ctx context.Context, in *region.CreateRegionRequest, opts ...grpc.CallOption) (*region.CreateRegionResponse, error)
	// 修改国家地区
	Update(ctx context.Context, in *region.UpdateRegionRequest, opts ...grpc.CallOption) (*region.UpdateRegionResponse, error)
	// 获取国家地区
	Get(ctx context.Context, in *region.GetRegionRequest, opts ...grpc.CallOption) (*region.GetRegionResponse, error)
	// 获取国家地区管理列表
	List(ctx context.Context, in *region.ListRegionsRequest, opts ...grpc.CallOption) (*region.ListRegionsResponse, error)
	// 获取全部国家地区
	ListAll(ctx context.Context, in *region.ListAllRegionsRequest, opts ...grpc.CallOption) (*region.ListAllRegionsResponse, error)
	// 调整国家地区排序
	Reorder(ctx context.Context, in *region.ReorderRegionRequest, opts ...grpc.CallOption) (*region.ReorderRegionResponse, error)
}

type regionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionServiceClient(cc grpc.ClientConnInterface) RegionServiceClient {
	return &regionServiceClient{cc}
}

func (c *regionServiceClient) Create(ctx context.Context, in *region.CreateRegionRequest, opts ...grpc.CallOption) (*region.CreateRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(region.CreateRegionResponse)
	err := c.cc.Invoke(ctx, RegionService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) Update(ctx context.Context, in *region.UpdateRegionRequest, opts ...grpc.CallOption) (*region.UpdateRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(region.UpdateRegionResponse)
	err := c.cc.Invoke(ctx, RegionService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) Get(ctx context.Context, in *region.GetRegionRequest, opts ...grpc.CallOption) (*region.GetRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(region.GetRegionResponse)
	err := c.cc.Invoke(ctx, RegionService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) List(ctx context.Context, in *region.ListRegionsRequest, opts ...grpc.CallOption) (*region.ListRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(region.ListRegionsResponse)
	err := c.cc.Invoke(ctx, RegionService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) ListAll(ctx context.Context, in *region.ListAllRegionsRequest, opts ...grpc.CallOption) (*region.ListAllRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(region.ListAllRegionsResponse)
	err := c.cc.Invoke(ctx, RegionService_ListAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) Reorder(ctx context.Context, in *region.ReorderRegionRequest, opts ...grpc.CallOption) (*region.ReorderRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(region.ReorderRegionResponse)
	err := c.cc.Invoke(ctx, RegionService_Reorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionServiceServer is the server API for RegionService service.
// All implementations must embed UnimplementedRegionServiceServer
// for forward compatibility.
//
// 国家地区服务
type RegionServiceServer interface {
	// 创建国家地区
	Create(context.Context, *region.CreateRegionRequest) (*region.CreateRegionResponse, error)
	// 修改国家地区
	Update(context.Context, *region.UpdateRegionRequest) (*region.UpdateRegionResponse, error)
	// 获取国家地区
	Get(context.Context, *region.GetRegionRequest) (*region.GetRegionResponse, error)
	// 获取国家地区管理列表
	List(context.Context, *region.ListRegionsRequest) (*region.ListRegionsResponse, error)
	// 获取全部国家地区
	ListAll(context.Context, *region.ListAllRegionsRequest) (*region.ListAllRegionsResponse, error)
	// 调整国家地区排序
	Reorder(context.Context, *region.ReorderRegionRequest) (*region.ReorderRegionResponse, error)
	mustEmbedUnimplementedRegionServiceServer()
}

// UnimplementedRegionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegionServiceServer struct{}

func (UnimplementedRegionServiceServer) Create(context.Context, *region.CreateRegionRequest) (*region.CreateRegionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRegionServiceServer) Update(context.Context, *region.UpdateRegionRequest) (*region.UpdateRegionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRegionServiceServer) Get(context.Context, *region.GetRegionRequest) (*region.GetRegionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRegionServiceServer) List(context.Context, *region.ListRegionsRequest) (*region.ListRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRegionServiceServer) ListAll(context.Context, *region.ListAllRegionsRequest) (*region.ListAllRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedRegionServiceServer) Reorder(context.Context, *region.ReorderRegionRequest) (*region.ReorderRegionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reorder not implemented")
}
func (UnimplementedRegionServiceServer) mustEmbedUnimplementedRegionServiceServer() {}
func (UnimplementedRegionServiceServer) testEmbeddedByValue()                       {}

// UnsafeRegionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegionServiceServer will
// result in compilation errors.
type UnsafeRegionServiceServer interface {
	mustEmbedUnimplementedRegionServiceServer()
}

func RegisterRegionServiceServer(s grpc.ServiceRegistrar, srv RegionServiceServer) {
	// If the following call panics, it indicates UnimplementedRegionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegionService_ServiceDesc, srv)
}

func _RegionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(region.CreateRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).Create(ctx, req.(*region.CreateRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(region.UpdateRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).Update(ctx, req.(*region.UpdateRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(region.GetRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).Get(ctx, req.(*region.GetRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(region.ListRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).List(ctx, req.(*region.ListRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(region.ListAllRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_ListAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).ListAll(ctx, req.(*region.ListAllRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_Reorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(region.ReorderRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).Reorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionService_Reorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).Reorder(ctx, req.(*region.ReorderRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegionService_ServiceDesc is the grpc.ServiceDesc for RegionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_base.RegionService",
	HandlerType: (*RegionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RegionService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RegionService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RegionService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RegionService_List_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _RegionService_ListAll_Handler,
		},
		{
			MethodName: "Reorder",
			Handler:    _RegionService_Reorder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_base.proto",
}
