// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/internal/logic/languageservice"
	"oa.98ent.com/p9/platform-base/rpc/internal/svc"
	"oa.98ent.com/p9/platform-base/rpc/pb/base"
	"oa.98ent.com/p9/platform-base/rpc/pb/base/language"
)

type LanguageServiceServer struct {
	svcCtx *svc.ServiceContext
	base.UnimplementedLanguageServiceServer
}

func NewLanguageServiceServer(svcCtx *svc.ServiceContext) *LanguageServiceServer {
	return &LanguageServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建语言
func (s *LanguageServiceServer) Create(ctx context.Context, in *language.CreateLanguageRequest) (*language.CreateLanguageResponse, error) {
	l := languageservicelogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

// 修改语言
func (s *LanguageServiceServer) Update(ctx context.Context, in *language.UpdateLanguageRequest) (*language.UpdateLanguageResponse, error) {
	l := languageservicelogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

// 获取语言
func (s *LanguageServiceServer) Get(ctx context.Context, in *language.GetLanguageRequest) (*language.GetLanguageResponse, error) {
	l := languageservicelogic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

// 获取语言管理列表
func (s *LanguageServiceServer) List(ctx context.Context, in *language.ListLanguagesRequest) (*language.ListLanguagesResponse, error) {
	l := languageservicelogic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 获取全部语言
func (s *LanguageServiceServer) ListAll(ctx context.Context, in *language.ListAllLanguagesRequest) (*language.ListAllLanguagesResponse, error) {
	l := languageservicelogic.NewListAllLogic(ctx, s.svcCtx)
	return l.ListAll(in)
}

// 调整语言排序
func (s *LanguageServiceServer) Reorder(ctx context.Context, in *language.ReorderLanguageRequest) (*language.ReorderLanguageResponse, error) {
	l := languageservicelogic.NewReorderLogic(ctx, s.svcCtx)
	return l.Reorder(in)
}
